                           __  __                         _ 
 ___ _   _ _ __   ___ _ __|  \/  | __ _ _ __  _   _  __ _| |
/ __| | | | '_ \ / _ \ '__| |\/| |/ _` | '_ \| | | |/ _` | |
\__ \ |_| | |_) |  __/ |  | |  | | (_| | | | | |_| | (_| | |
|___/\__,_| .__/ \___|_|  |_|  |_|\__,_|_| |_|\__,_|\__,_|_|
          |_|                                                                                                            _ 

* Introduction

SuperMan is a project manager for emacs based on org-mode. See
[[./superInterview.org]] for a discussion of the definition of a project.
Project specific information is managed in a file whose place is
defined by the variable superman-profile. See M-x describe-variable
RET superman-profile RET for the current value. The value of the
variable needs to be set in you .emacs file.

* Project view 
** Adding information

Press `N' to add a new item. If the point is in a section add an item
in this section, for example call superman-capture-document when the
cursor is in the section Documents.

** Git control

SuperMan provides an interface to git control a project.

*** Initialization

In the project view buffer press "GI" for git initialize.

*** Adding files to the repository

* Window configurations

Superman implements a simple approach to save and restore project specific window-configurations.

** Save the current configuration

M-x superman-save-config RET 

** Restore a window configuration

M-x superman-switch-config RET

** Add a configuration to a single project 

** Add a configuration to all projects in a category
#+BEGIN_EXAMPLE
*** Courses
    :PROPERTIES:
    :CATEGORY: Teaching
    :Location: ~/public_html/Teaching/
    :CONFIG:   INDEX / ./lecturenotes | TODO / TIMELINE
    :END:
#+END_EXAMPLE
