---
title: "Comorbidity with drugs"
author: "Helle Højmark Eriksen"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Comorbidity with drugs}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

This vignette introduces the use of the function comorbidityDrugs.

## Example

Find patients who have received drugs with atc codes starting with 'S01' or 'R03' and report the date of the first occurrence for each patient.

```{r,eval=FALSE}
library(heaven)
library(data.table)
dat<-data.table(pnr=1:22, atc=rep(c("A01AB04", "A03AA04", "N02BE01", "M01AE01", "R03CC02", "S01XA20"),each=5), eksd=c("2001-01-18","2002-02-20","2002-01-10","2001-09-10","1999-09-10"))
dat[,eksd:=as.Date(eksd)]
a<-comorbidityDrugs(dat, code=c('S01', 'R03'))
```

Output of the funktion is a data.table with the columns pnr, atc and eksd containing the rows where the atc code is starting with 'S01' or 'R03'.

```{r,echo=FALSE}
library(heaven)
library(data.table)
<<<<<<< HEAD
suppressWarnings(dat<-data.table(pnr=1:22, atc=rep(c("A01AB04", "A03AA04", "N02BE01", "M01AE01", "R03CC02", "S01XA20"),each=5), eksd=c("2001-01-18","2002-02-20","2002-01-10","2001-09-10","1999-09-10")))
dat[,eksd:=as.Date(eksd)]
=======
dat <- data.table(pnr=1:30,
                  atc=rep(c("A01AB04", "A03AA04", "N02BE01", "M01AE01", "R03CC02", "S01XA20"),each=5),
		  eksd=as.Date(c("2001-01-18","2002-02-20","2002-01-10","2001-09-10","1999-09-10")))
>>>>>>> bae3c8e91cb285cc93a73e69525eae61e262d30e
a<-comorbidityDrugs(dat, code=c('S01', 'R03'))
a 
```


