* Only one recept
** Old version with bugs
#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R  :results output raw drawer  :exports both  :session *R* :cache yes  :eval always
  library(heaven)
  library(data.table)
  library(Publish)
  lmdb0 <- data.table(pnr=8,
		      eksd=as.Date("2005-01-25"),
		      apk=1,
		      atc="C10AA01",
		      strnum=10,
		      packsize=0.0999998)
  org("Purchases data:")
  org(lmdb0)
#+END_SRC

#+RESULTS[<2019-09-10 13:10:34> bcdedcf7007e53f21b2d2cbd27cd7f27a4c68a7d]:
:RESULTS:

Purchases data:
|  pnr |       eksd | apk |     atc | strnum |  packsize |
|------+------------+-----+---------+--------+-----------|
|    8 | 2005-01-25 |   1 | C10AA01 |     10 | 0.0999998 |
:END:

#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R  :results output raw drawer  :exports both  :session *R* :cache yes  :eval always
  simva <- list(atc="C10AA01",maxdepot=8000,
		period=as.Date(c("2004-01-01","2015-12-31")),
		prescriptionwindow=2, ## consider 2 previous purchases and current
		doses=list(value=c(10,20,30),min=c(5,10,15),max=c(20,40,60),def=c(10,20,30)))
  ## Rcpp::sourceCpp("~/research/SoftWare/heaven/src/innerMedicinMacro.cpp")
  x <- medicinMacro(drugs=list(simva=simva),drugdb=lmdb0,admdb=NULL)
  org("Estimated doses data using R:")
  org(x$simva[])
#+END_SRC

#+RESULTS[<2019-09-10 13:09:17> ece460e41c1877bee4b3d36a40c5e09536e1e440]:
:RESULTS:

Estimated doses data using R:
|  pnr | dose |   firstday |    lastday | exposure.days |
|------+------+------------+------------+---------------|
|    8 |   10 | 2005-01-25 | 2005-01-24 |       -1 days |
:END:

** Fixing/testing

#+BEGIN_SRC R  :results output raw drawer  :exports both  :session *R* :cache yes 
  lmdb0 <- data.table(pnr=8,
		      eksd=as.Date("2005-01-25"),
		      apk=1,
		      atc="C10AA01",
		      strnum=10,
		      packsize=0.0999998)
  simva <- list(atc="C10AA01",maxdepot=8000,
		period=as.Date(c("2004-01-01","2015-12-31")),
		prescriptionwindow=2, ## consider 2 previous purchases and current
		doses=list(value=c(10,20,30),min=c(5,10,15),max=c(20,40,60),def=c(10,20,30)))
  Rcpp::sourceCpp("~/Rpackages/heaven/src/innerMedicinMacro-fixing.cpp") # Using fixed version
  source("~/Rpackages/heaven/R/medicinMacro.R")
  x <- medicinMacro(drugs=list(simva=simva),drugdb=lmdb0,admdb=NULL)
  org("Estimated doses data using R:") 
  org(x$simva[])
#+END_SRC

#+RESULTS[<2019-09-10 13:10:39> 58de0c26be2c70d010e42543d45ddfa911bd3abe]:
:RESULTS:

Estimated doses data using R:
|  pnr | dose |   firstday |    lastday | exposure.days |
|------+------+------------+------------+---------------|
|    8 |   10 | 2005-01-25 | 2005-01-25 |        0 days |
:END:




* More than one recept

#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R  :results output raw drawer  :exports both  :session *R* :cache yes  :eval always
library(heaven)
library(data.table)
library(Publish)
lmdb <- data.table(pnr=rep(8,5),
                   eksd=as.Date(c("2005-01-25","2005-03-03","2006-01-11","2006-04-15","2006-07-31")),
                   apk=rep(1,5),
                   atc=rep("C10AA01",5),strnum=c(10,10,10,10,20),packsize=rep(100,5))
org("Purchases data:")
org(lmdb)
#+END_SRC

#+RESULTS[<2019-09-03 08:26:47> fb7236a55ccfda8a7b15057ef02cfbae62006211]:
:results:

Purchases data:
|  pnr |       eksd | apk |     atc | strnum | packsize |
|------+------------+-----+---------+--------+----------|
|    8 | 2005-01-25 |   1 | C10AA01 |     10 |      100 |
|    8 | 2005-03-03 |   1 | C10AA01 |     10 |      100 |
|    8 | 2006-01-11 |   1 | C10AA01 |     10 |      100 |
|    8 | 2006-04-15 |   1 | C10AA01 |     10 |      100 |
|    8 | 2006-07-31 |   1 | C10AA01 |     20 |      100 |
:end:

#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R  :results output raw drawer  :exports both  :session *R* :cache yes  :eval always
simva <- list(atc="C10AA01",maxdepot=8000,
              period=as.Date(c("2004-01-01","2015-12-31")),
              prescriptionwindow=2, ## consider 2 previous purchases and current
              doses=list(value=c(10,20,30),min=c(5,10,15),max=c(20,40,60),def=c(10,20,30)))
              ## doses=list(value=c(10,20,30),min=c(10,20,30),max=c(10,20,30),def=c(10,20,30)))
Rcpp::sourceCpp("~/research/SoftWare/heaven/src/innerMedicinMacro.cpp")
x <- medicinMacro(drugs=list(simva=simva),drugdb=lmdb,admdb=NULL,verbose=1)
org("Estimated doses data using R:")
org(x$simva[])
#+END_SRC

#+RESULTS[<2019-09-03 09:03:42> 7eb771328af5e63af86d639942af553ebb002519]:
:results:
==============subject: = 0===============

Date    : 1980-01-26
Next    : 1980-03-03
Hospital: 0
# Days  : 37
Purchase: 1000
Stash   : 0
Total   : 1000
Dosis   : 10
Covered : 100 days 
Reached : 1980-05-04
Start   : 1980-01-26
End     : 1980-03-02
---------------


Date    : 1980-03-03
Next    : 1981-01-11
Hospital: 0
# Days  : 314
Purchase: 1000
Stash   : 630
Total   : 1630
Reach   : 1
Weight  : 1
Dosis   : 20
Covered : 81 days 
Reached : 1980-05-22
Start   : 1980-03-03
End     : 1980-05-22
---------------


Date    : 1981-01-11
Next    : 1981-04-15
Hospital: 0
# Days  : 94
Purchase: 1000
Stash   : 0
Total   : 1000
Reach   : 1
Weight  : 1
Dosis   : 5
Covered : 200 days 
Reached : 1981-07-29
Start   : 1981-01-11
End     : 1981-04-14
---------------


Date    : 1981-04-15
Next    : 1981-07-31
Hospital: 0
# Days  : 107
Purchase: 1000
Stash   : 530
Total   : 1530
Reach   : 1
Weight  : 1
Dosis   : 5
Covered : 306 days 
Reached : 1982-02-14
Start   : 1981-01-11
End     : 1981-07-30
---------------


Date    : 1981-07-31
Hospital: 0
# Days  : -9
Purchase: 2000
Stash   : 995
Total   : 2995
Reach   : 1
Weight  : 0
Dosis   : 10
Covered : 299 days 
Reached : 1982-05-25
Start   : 1981-07-31
End     : 1982-05-25
---------------

Estimated doses data using R:
|  pnr | dose |   firstday |    lastday | exposure.days |
|------+------+------------+------------+---------------|
|    8 |   10 | 2005-01-25 | 2005-03-02 |       36 days |
|    8 |   20 | 2005-03-03 | 2005-05-22 |       80 days |
|    8 |    0 | 2005-05-23 | 2006-01-10 |      232 days |
|    8 |    5 | 2006-01-11 | 2006-07-30 |      200 days |
|    8 |   10 | 2006-07-31 | 2007-05-25 |      298 days |
:end:


#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R  :results output raw drawer  :exports both  :session *R* :cache yes  :eval always
adm <- simAdmissionData(4)
y <- xrecepter(drugdb=lmdb,
               adm=adm,
               atc="C10AA01",
               period=c("'2004jan01'd","'2015dec31'd"),
               maxdepot=8000,
               value=c(10,20,30,40),
               min=c(5,10,15,20),
               max=c(20,40,60,80),
               def=c(10,20,30,40))
org("Estimated doses data using SAS:")
org(y)
#+END_SRC

#+RESULTS[<2019-09-01 19:46:13> cc90e30645b51ba052219c7f7e1327f529705ea4]:
:results:
|  pnr | dose |   firstday |    lastday | exposure.days |
|------+------+------------+------------+---------------|
|    8 |   10 | 2005-01-25 | 2005-03-02 |       36 days |
|    8 |   20 | 2005-03-03 | 2005-05-23 |       81 days |
|    8 |    5 | 2006-01-11 | 2006-04-14 |       93 days |
|    8 |   10 | 2006-04-15 | 2007-04-06 |      356 days |
:end:


* Two purchases

** Two purchases with overlap
#+BEGIN_SRC R  :results output raw drawer  :exports results  :session *R* :cache yes 
  lmdb1 <- data.table(pnr=c(8,8),
		      eksd=as.Date(c("2005-01-16","2005-01-19")),
		      apk=c(1,1),
		      atc=c("C10AA01", "C10AA01"),
		      strnum=c(10,10),
		      packsize=c(5,5)) # 0.0999998)
  simva1 <- list(atc="C10AA01",maxdepot=8000,
		 period=as.Date(c("2004-01-01","2015-12-31")),
		 maxdepot = 10000, # Does this effect anything? No...
		 prescriptionwindow=2, ## consider 2 previous purchases and current
		 doses=list(value=c(10,20,30),min=c(10,10,15),max=c(10,40,60),def=c(10,20,30))) # Fixing dosis

  org("Two purchases with overlap")
  org(lmdb1)
  org("Old version")
  Rcpp::sourceCpp("~/Rpackages/heaven/src/innerMedicinMacro.cpp")
  org(medicinMacro(drugs=list(simva1=simva1),drugdb=lmdb1,admdb=NULL)$simva1)
  org("Corrected version")
  Rcpp::sourceCpp("~/Rpackages/heaven/src/innerMedicinMacro-fixing.cpp") # Using "fixed" version
  org(medicinMacro(drugs=list(simva1=simva1),drugdb=lmdb1,admdb=NULL)$simva1)
#+END_SRC

#+RESULTS[<2019-09-10 10:44:13> 95494132cce740281169d2aa47183e22a423ff8a]:
:RESULTS:

Two purchases with overlap
|  pnr |       eksd | apk |     atc | strnum | packsize |
|------+------------+-----+---------+--------+----------|
|    8 | 2005-01-16 |   1 | C10AA01 |     10 |        5 |
|    8 | 2005-01-19 |   1 | C10AA01 |     10 |        5 |

Old version
|  pnr | dose |   firstday |    lastday | exposure.days |
|------+------+------------+------------+---------------|
|    8 |   10 | 2005-01-16 | 2005-01-25 |        9 days |

Corrected version
|  pnr | dose |   firstday |    lastday | exposure.days |
|------+------+------------+------------+---------------|
|    8 |   10 | 2005-01-16 | 2005-01-26 |       10 days |
:END:

** Two purchases without overlap

#+BEGIN_SRC R  :results output raw drawer  :exports results  :session *R* :cache yes 
org("Two purchases without overlap")
lmdb1$eksd[2] <- as.Date("2005-01-23")
org(lmdb1)
org("Old version")
Rcpp::sourceCpp("~/Rpackages/heaven/src/innerMedicinMacro.cpp")
org(medicinMacro(drugs=list(simva1=simva1),drugdb=lmdb1,admdb=NULL)$simva1)
org("Corrected version")
Rcpp::sourceCpp("~/Rpackages/heaven/src/innerMedicinMacro-fixing.cpp") # Using "fixed" version
org(medicinMacro(drugs=list(simva1=simva1),drugdb=lmdb1,admdb=NULL)$simva1)
#+END_SRC

#+RESULTS[<2019-09-10 10:44:37> f6974b51de145bc04fac4aa8a0d3dc5c3a7ff3b7]:
:RESULTS:

Two purchases without overlap
|  pnr |       eksd | apk |     atc | strnum | packsize |
|------+------------+-----+---------+--------+----------|
|    8 | 2005-01-16 |   1 | C10AA01 |     10 |        5 |
|    8 | 2005-01-23 |   1 | C10AA01 |     10 |        5 |

Old version
|  pnr | dose |   firstday |    lastday | exposure.days |
|------+------+------------+------------+---------------|
|    8 |   10 | 2005-01-16 | 2005-01-20 |        4 days |
|    8 |    0 | 2005-01-21 | 2005-01-22 |        1 days |
|    8 |   10 | 2005-01-23 | 2005-01-27 |        4 days |

Corrected version
|  pnr | dose |   firstday |    lastday | exposure.days |
|------+------+------------+------------+---------------|
|    8 |   10 | 2005-01-16 | 2005-01-21 |        5 days |
|    8 |    0 | 2005-01-21 | 2005-01-23 |        2 days |
|    8 |   10 | 2005-01-23 | 2005-01-28 |        5 days |
:END:


* Different doses

A patient purchases 5 pills of strength 10 with daily dosis 10; this gives a supply for 5 days. But then after 2 days, he purchases 5 pills of strength 30 with dose 15; this gives (in isolation) supplies for an additional 10 days. If we assume that the patient has changed his daily dosis when purchasing the new pills, it means that the stash of 3 pills after 2 days is only enough for 2 days -- because now he needs a daily dosis of 15. Correct?
#+BEGIN_SRC R  :results output raw drawer  :exports results  :session *R* :cache yes 
  lmdb1 <- data.table(pnr=c(8,8),
		      eksd=as.Date(c("2005-01-16","2005-01-18")),
		      apk=c(1,1),
		      atc=c("C10AA01", "C10AA01"),
		      strnum=c(10,30),
		      packsize=c(5,5))
  simva1 <- list(atc="C10AA01",maxdepot=8000,
		 period=as.Date(c("2004-01-01","2015-12-31")),
		 prescriptionwindow=2, ## consider 2 previous purchases and current
		 doses=list(value=c(10,30),min=c(10,15),max=c(10,15),def=c(10,15))) # Fixing doses for now

  org("Old version")
  Rcpp::sourceCpp("~/Rpackages/heaven/src/innerMedicinMacro.cpp")
  org(medicinMacro(drugs=list(simva1=simva1),drugdb=lmdb1,admdb=NULL)$simva1)
  org("Corrected version")
  Rcpp::sourceCpp("~/Rpackages/heaven/src/innerMedicinMacro-fixing.cpp") # Using "fixed" version
  org(medicinMacro(drugs=list(simva1=simva1),drugdb=lmdb1,admdb=NULL, verbose=F)$simva1)
#+END_SRC

#+RESULTS[<2019-09-10 15:18:47> 52d0dfd47c9ab41e0e2327d36d6a32332dd88679]:
:RESULTS:

Old version
|  pnr | dose |   firstday |    lastday | exposure.days |
|------+------+------------+------------+---------------|
|    8 |   10 | 2005-01-16 | 2005-01-17 |        1 days |
|    8 |   15 | 2005-01-18 | 2005-01-29 |       11 days |

Corrected version
|  pnr | dose |   firstday |    lastday | exposure.days |
|------+------+------------+------------+---------------|
|    8 |   10 | 2005-01-16 | 2005-01-18 |        2 days |
|    8 |   15 | 2005-01-18 | 2005-01-30 |       12 days |
:END:


* Purchasing several different drug packages

What happens when we buy the same drug but with different doses?

#+BEGIN_SRC R  :results output raw drawer  :exports results  :session *R* :cache yes 
  lmdb1 <- data.table(pnr=c(8,8),
		      eksd=as.Date(c("2005-01-10","2005-01-10")),
		      apk=c(1,1),
		      atc=c("C10AA01", "C10AA01"),
		      strnum=c(10,30),
		      packsize=c(5,5))
  simva1 <- list(atc="C10AA01",maxdepot=8000,
		 period=as.Date(c("2004-01-01","2015-12-31")),
		 prescriptionwindow=2, ## consider 2 previous purchases and current
		 doses=list(value=c(10,30),min=c(10,15),max=c(10,15),def=c(10,15))) # Fixing doses for now
  org("Different types of the same drug purchased on the same day:")
  org("Old version")
  Rcpp::sourceCpp("~/Rpackages/heaven/src/innerMedicinMacro.cpp")
  org(medicinMacro(drugs=list(simva1=simva1),drugdb=lmdb1,admdb=NULL, verbose=F)$simva1)
  org("Corrected version")
  Rcpp::sourceCpp("~/Rpackages/heaven/src/innerMedicinMacro-fixing.cpp") # Using "fixed" version
  org(medicinMacro(drugs=list(simva1=simva1),drugdb=lmdb1,admdb=NULL, verbose=F)$simva1)
#+END_SRC

#+RESULTS[<2019-09-10 15:50:42> 491bf89217544ad87a6aa62eca720a8655f431a9]:
:RESULTS:

Different types of the same drug purchased on the same day:

Old version
|  pnr | dose |   firstday |    lastday | exposure.days |
|------+------+------------+------------+---------------|
|    8 |   10 | 2005-01-10 | 2005-01-29 |       19 days |

Corrected version
|  pnr | dose |   firstday |    lastday | exposure.days |
|------+------+------------+------------+---------------|
|    8 |   10 | 2005-01-10 | 2005-01-30 |       20 days |
:END:

In this case, the maximum number of days exposed is used as the number of exposure days (so this "override" the default daily doses of the stronger drug). This is not the same behaviour as when the two different drugs are purchsed on /different/ dates, but might still make sense. 

Case with one purchase and then two purchases on the same day a bit later:

#+BEGIN_SRC R  :results output raw drawer  :exports results  :session *R* :cache yes 
  lmdb1 <- data.table(pnr=c(8,8,8),
		      eksd=as.Date(c("2005-01-13", "2005-01-15","2005-01-15")),
		      apk=rep(1,3),
		      atc=rep("C10AA01", 3),
		      strnum=c(10,10,30),
		      packsize=rep(5,3))
  simva1 <- list(atc="C10AA01",maxdepot=8000,
		 period=as.Date(c("2004-01-01","2015-12-31")),
		 prescriptionwindow=2, ## consider 2 previous purchases and current
		 doses=list(value=c(10,30),min=c(10,15),max=c(10,15),def=c(10,15))) # Fixing doses for now
  org("Old version")
  Rcpp::sourceCpp("~/Rpackages/heaven/src/innerMedicinMacro.cpp")
  org(medicinMacro(drugs=list(simva1=simva1),drugdb=lmdb1,admdb=NULL, verbose=F)$simva1)
  org("Corrected version")
  Rcpp::sourceCpp("~/Rpackages/heaven/src/innerMedicinMacro-fixing.cpp") # Using "fixed" version
  org(medicinMacro(drugs=list(simva1=simva1),drugdb=lmdb1,admdb=NULL, verbose=F)$simva1)
#+END_SRC 

#+RESULTS[<2019-09-10 15:54:48> dabc810eda1e1a654c2c84986185f7180531f5d1]:
:RESULTS:

Old version
|  pnr | dose |   firstday |    lastday | exposure.days |
|------+------+------------+------------+---------------|
|    8 |   10 | 2005-01-13 | 2005-02-06 |       24 days |

Corrected version
|  pnr | dose |   firstday |    lastday | exposure.days |
|------+------+------------+------------+---------------|
|    8 |   10 | 2005-01-13 | 2005-02-07 |       25 days |
:END:

* Calculating the estimated average daily dose 

Need to test the different cases. Don't understand when we use case 1 and 2?
