# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Matcher <- function(Ncontrols, Tcontrols, Ncases, endFollowUp, caseIndex, controls, cases, Ndateterms, datescases, datescontrols, Ndurationterms, durationcases, durationcontrols, durationMin) {
    .Call('_heaven_Matcher', PACKAGE = 'heaven', Ncontrols, Tcontrols, Ncases, endFollowUp, caseIndex, controls, cases, Ndateterms, datescases, datescontrols, Ndurationterms, durationcases, durationcontrols, durationMin)
}

daysnonhosp <- function(id, pdate, iddates, inddto, uddto) {
    .Call('_heaven_daysnonhosp', PACKAGE = 'heaven', id, pdate, iddates, inddto, uddto)
}

#' @description Inner process of medicin macro
#' @title The heart of the medicin macro
#' @param dat data set
#' @param admdat admission data
#' @param doses doses
#' @param idunique unique subject ids
#' @param prescriptionwindow prescription window
#' @param maxdepot see medicine macro
#' @author Helene Charlotte Rytgaard and Thomas Alexander Gerds
#' @export
innerMedicinMacro <- function(dat, admdat, doses, idunique, prescriptionwindow, maxdepot) {
    .Call('_heaven_innerMedicinMacro', PACKAGE = 'heaven', dat, admdat, doses, idunique, prescriptionwindow, maxdepot)
}

na_locf <- function(x) {
    .Call('_heaven_na_locf', PACKAGE = 'heaven', x)
}

nccSamplingCpp <- function(pnr, time, status, Tstart, exposureWindow, Ncontrols = 10L) {
    .Call('_heaven_nccSamplingCpp', PACKAGE = 'heaven', pnr, time, status, Tstart, exposureWindow, Ncontrols)
}

split2 <- function(pnrnum, inn, out, event, mergevar, split, numcov) {
    .Call('_heaven_split2', PACKAGE = 'heaven', pnrnum, inn, out, event, mergevar, split, numcov)
}

splitDate <- function(inn, out, event, mergevar, seq, varname) {
    .Call('_heaven_splitDate', PACKAGE = 'heaven', inn, out, event, mergevar, seq, varname)
}

splitFT <- function(pnrnum, inn, out, event, mergevar, Spnrnum, val, start, end, num, numcov, default_) {
    .Call('_heaven_splitFT', PACKAGE = 'heaven', pnrnum, inn, out, event, mergevar, Spnrnum, val, start, end, num, numcov, default_)
}

