# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

daysnonhosp <- function(id, pdate, iddates, inddto, uddto) {
    .Call('heaven_daysnonhosp', PACKAGE = 'heaven', id, pdate, iddates, inddto, uddto)
}

#' @description Inner process of medicin macro
#' @title The heart of the medicin macro
#' @param dat data set
#' @param admdat admission data
#' @param doses doses
#' @param idunique unique subject ids
#' @param N sample size
#' @param maxdepot see medicine macro
#' @param collapse If \code{TRUE} collapse admission periods when there is not a single day out of hospital in between.
#' @author Helene Charlotte Rytgaard
#' @export
innerprocess <- function(dat, admdat, doses, idunique, N, maxdepot, collapse) {
    .Call('heaven_innerprocess', PACKAGE = 'heaven', dat, admdat, doses, idunique, N, maxdepot, collapse)
}

#' @description Fast matcher
#' @title Matcher
#' @author Christian Torp-Pedersen
#' @export
Matcher <- function(Ncontrols, Tcontrols, Ncases, reuseControls, controlIndex, caseIndex, controls, cases, NoIndex) {
    .Call('heaven_Matcher', PACKAGE = 'heaven', Ncontrols, Tcontrols, Ncases, reuseControls, controlIndex, caseIndex, controls, cases, NoIndex)
}

#' @description Split2
#' @title Split2
#' @author Christian Torp-Pedersen
#' @export
split2 <- function(pnr, inn, out, dato, dead) {
    .Call('heaven_split2', PACKAGE = 'heaven', pnr, inn, out, dato, dead)
}

timesTwo <- function(x) {
    .Call('heaven_timesTwo', PACKAGE = 'heaven', x)
}

