# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

daysnonhosp <- function(id, pdate, iddates, inddto, uddto) {
    .Call('_heaven_daysnonhosp', PACKAGE = 'heaven', id, pdate, iddates, inddto, uddto)
}

#' @title Inner process function.
#' @author Helene Charlotte Rytgaard
#' @export
innerprocess <- function(dat, admdat, doses, idunique, treatname, N, maxdepot, collapse) {
    .Call('_heaven_innerprocess', PACKAGE = 'heaven', dat, admdat, doses, idunique, treatname, N, maxdepot, collapse)
}

#' @title Matcher
#' @author Christian Torp-Pedersen
#' @export
Matcher <- function(Ncontrols, Tcontrols, Ncases, reuseControls, controlIndex, caseIndex, controls, cases, NoIndex) {
    .Call('_heaven_Matcher', PACKAGE = 'heaven', Ncontrols, Tcontrols, Ncases, reuseControls, controlIndex, caseIndex, controls, cases, NoIndex)
}

#' @title Split2
#' @author Christian Torp-Pedersen
#' @export
split2 <- function(pnr, inn, out, dato, dead) {
    .Call('_heaven_split2', PACKAGE = 'heaven', pnr, inn, out, dato, dead)
}

modifyDataFrame <- function(names) {
    .Call('_heaven_modifyDataFrame', PACKAGE = 'heaven', names)
}

timesTwo <- function(x) {
    .Call('_heaven_timesTwo', PACKAGE = 'heaven', x)
}

