#' @title trialSimulation
#' @description 
#' This function was generated by CHATGPT based on the following request:
#' I need a program to produce data for a simulated trial of n individuals. 
#' It should have baseline data of sex (equal distribution) and age (between 50 
#' and 80 years).  At baseline individuals are randomly given treatment A or B.  
#' During follow-up of five years 50% have the outcome Y (0/1), 30% are censored 
#' at varying times and the final 20% have the competing risk of death. All 
#' three outcomes occur randomly during the trial except for treatment A that 
#' reduces the risk of outcome by 50% when the actual treatment is A.  
#' During follow-up at random times 30% discontinue the allocated treatment 
#' and half of these switch to ther other treatment.  There is further another 
#' time dependent variable T which has no effect on outcomes, but which occur 
#' for 50% of indivuals during about a year sometime during the five year period.
#'
#' The product should be three datasets.  The baseline  data have age, sex 
#' and baseline treatment.  The outcome dataset should have four variables: 
#' ID, Y, Censor and Compete - For the columns of Censor, 
#' Compete and Y the value is the time of the outcome.  The final dataset is 
#' the time dependent variables of the two treatments and the extra variable T.  
#' This dataset should have ID, start, end, value=1 and variable (T, A, B)
#' @usage
#' trialSimulation(seed=123,n=1000)
#' @author Christian Torp-Pedersen
#' @param seed is random seed
#' @param n is number of individuals
#' @return
#' The function returns a list of three datasets corresponding to baseline,
#' time dependent variables (dep_vars) and outcomes
#' @examples
#' library(data.table)
#' trialSimulation(seed=2,n=10)
#' @export
# Simulate trial data (R)
# Outputs three data.frames (baseline, outcomes, time_dependent)
# Usage: source('simulated_trial_data.R'); res <- trialSimulation(n = 1000, seed = 42)

# Simulate trial data (R)
# Outputs three data.frames (baseline, outcomes, time_dependent)
# Usage: source('simulated_trial_data.R'); res <- trialSimulation(n = 1000, seed = 42)

trialSimulation <- function(n = 1000, followup = 5, seed = 123) {
  #if(!is.null(seed)) set.seed(seed)
  
  # 1) Baseline
  ID <- seq_len(n)
  sex <- sample(c("M","F"), n, replace = TRUE)  # equal-ish
  age <- runif(n, min = 50, max = 80)
  trt0 <- sample(c("A","B"), n, replace = TRUE)
  baseline <- data.frame(ID = ID, age = age, sex = sex, trt0 = trt0)
  
  # 2) Event-time generation using exponential cause-specific times
  base_rates <- c(Y = 0.5, C = 0.3, D = 0.2)
  scale <- 0.3
  rates <- base_rates * scale
  
  # Treatment A reduces risk of outcome Y by 50%
  time_to_Y <- numeric(n)
  time_to_C <- rexp(n, rate = rates["C"])
  time_to_D <- rexp(n, rate = rates["D"])
  for(i in seq_len(n)){
    lamY <- rates["Y"] * ifelse(trt0[i] == "A", 0.5, 1)
    time_to_Y[i] <- rexp(1, rate = lamY)
  }
  time_to_Y[time_to_Y <= 0] <- 1e-6
  time_to_C[time_to_C <= 0] <- 1e-6
  time_to_D[time_to_D <= 0] <- 1e-6
  
  event_time <- pmin(time_to_Y, time_to_C, time_to_D, followup)
  event_type <- ifelse(event_time == time_to_Y & time_to_Y <= pmin(time_to_C, time_to_D, followup), "Y",
                       ifelse(event_time == time_to_C & time_to_C <= pmin(time_to_Y, time_to_D, followup), "C",
                              ifelse(event_time == time_to_D & time_to_D <= pmin(time_to_Y, time_to_C, followup), "D","ADM")))
  
  outcomes <- data.frame(ID = ID,
                         Y = ifelse(event_type == "Y", event_time, NA_real_),
                         Censor = ifelse(event_type == "C" | event_type == "ADM", event_time, NA_real_),
                         Compete = ifelse(event_type == "D", event_time, NA_real_))
  
  # 3) Time-dependent intervals for treatments and variable T
  n_discontinue_target <- round(0.30 * n)
  disc_ids <- sample(ID, n_discontinue_target)
  is_discontinue <- ID %in% disc_ids
  disc_time <- rep(NA_real_, n)
  for(i in seq_len(n)){
    if(is_discontinue[i]){
      window_end <- min(event_time[i], followup)
      if(window_end > 0){
        disc_time[i] <- runif(1, min = 0.01, max = window_end)
        if(disc_time[i] >= window_end) disc_time[i] <- window_end - 1e-6
      } else {
        is_discontinue[i] <- FALSE
        disc_time[i] <- NA_real_
      }
    }
  }
  
  will_switch <- rep(FALSE, n)
  disc_indices <- which(!is.na(disc_time))
  if(length(disc_indices)>0){
    n_switch <- round(0.5 * length(disc_indices))
    switch_ids <- sample(disc_indices, n_switch)
    will_switch[switch_ids] <- TRUE
  }
  
  td_rows <- list()
  add_interval <- function(id, start, end, variable){
    if(is.na(start) | is.na(end)) return()
    if(end - start > 1e-8){
      td_rows[[length(td_rows) + 1]] <<- data.frame(ID = id, start = start, end = end, value = 1, variable = variable, stringsAsFactors = FALSE)
    }
  }
  
  for(i in seq_len(n)){
    et <- event_time[i]
    end_of_follow <- min(et, followup)
    if(is_discontinue[i] && !is.na(disc_time[i]) && disc_time[i] < end_of_follow){
      add_interval(ID[i], 0, disc_time[i], trt0[i])
      if(will_switch[i]){
        other_trt <- ifelse(trt0[i] == "A", "B", "A")
        add_interval(ID[i], disc_time[i], end_of_follow, other_trt)
      }
    } else {
      add_interval(ID[i], 0, end_of_follow, trt0[i])
    }
    
    # Add T variable (~50%) only if enough follow-up remains for ~1 year
    has_T <- runif(1) < 0.5
    if(has_T && end_of_follow > 1.1){
      max_start <- end_of_follow - 1.0
      if(max_start > 0){
        tstart <- runif(1, min = 0.01, max = max_start)
        tdur <- runif(1, min = 0.8, max = 1.2)
        tend <- min(tstart + tdur, end_of_follow)
        if(!is.na(tstart) && tend > tstart + 1e-8){
          add_interval(ID[i], tstart, tend, "T")
        }
      }
    }
  }
  
  if(length(td_rows) == 0){
    td <- data.frame(ID = integer(0), start = numeric(0), end = numeric(0), value = integer(0), variable = character(0), stringsAsFactors = FALSE)
  } else {
    td <- do.call(rbind, td_rows)
    td <- td[order(td$ID, td$start), ]
    rownames(td) <- NULL
  }
  
  eps <- 1e-8
  if(nrow(td)>0){
    library(dplyr)
    td <- td %>% group_by(ID, variable) %>% arrange(start) %>% mutate(
      start = pmax(start, 0),
      end = pmax(end, start + eps)
    ) %>% ungroup()
    td <- as.data.frame(td)
  }
  
  return(list(baseline = baseline, outcomes = outcomes, time_dependent = td))
}

# Example usage (uncomment to run):
res <- trialSimulation(n = 1000, seed = 123)
head(res$baseline)
head(res$outcomes)
head(res$time_dependent)






