* Introduction

The Danish National Prescription Registry (NCBI) provides
patient-level data on all prescription drugs sold in Danish
community pharmacies since 1994 citep:kildemoes2011danish. Effects and
side effects of drugs can be assessed in a Danish nation wide registry
study. For this the prescription data are linked to the cause of death
register and other Danish registries citep:thygesen2011introduction.\\

\noindent This document describes the /medicin macro/ by Christian
Torp-Pedersen, a complex algorithm for the computation of drug
exposure strength and length relative to a prespecified study period
$\period$ in calendar time. Note that the start of the study period has to be after the
start of the registry in 1994.




* Drug prescription data
label:sec:prescription

We describe the data of a single person who has purchased the drug of
interest at ${K}$ different dates in the study period \period. The
setup can easily be generalized to multiple patients. The set of
ordered drug purchase dates for one patient is denoted as
\begin{equation*}
{T}_1< \cdots< {T}_{K}.
\end{equation*}
Here \(K\) is the number of times the patient has purchased one or
more packages of the same drug product in the period \(\period\). One
package of each drug product is defined by the drug strength 
of the smallest unit (e.g., one pill or half a pill) and the amount of
such units that it contains. For each drug product we distinguish \(J\ge 1\)
different package types according to the different strengths: 
\begin{equation*}
\str_1 <\dots< \str_J.
\end{equation*}
Note that the original SAS macro allowed at most 4 different package
types but that the new implementation does not have this
limitation. For each drug strength \(\str_j\), the values \(\smin_j\),
\(\smax_j\), \(\styp_j\) define the minimal, maximal and typical dose
per day, respectively. \\

\noindent We now describe the total amount of drug purchased on date \(T_k\) and
the corresponding maximal number of days of supply. First, note that
since \(\smin_j\) is the minimal dosis, one unit of strength
\(\str_j\) can supply a maximal number of \((\str_j/\smin_j)\)
days. Next, consider that on date \(T_k\) the patient purchases
\(G_{jk}\) many packages of strength \(\str_j\). If the patients
purchases no package of strength j on date \(T_k\) then
\(G_{jk}=0\). Since each package may include a different number of
units, the total amount of units of strength \(\str_j\) purchased on date
\(T_k\) is given by
\begin{equation*}
m_{jk}=\sum_{g=1}^{G_{jk}}\text{(number of units in package \(g\))}
\end{equation*}
We convert this number to the scale defined by smallest units and
define the total amount of smallest units of strength \(\str_j\)
purchased on date \(T_k\) as
\begin{equation*}
n_{jk} = m_{jk} \frac{\str_j}{\smin_j}.
\end{equation*}
The total amount \(D_k\) of the drug purchased on date \(T_k\) is
given by the formula
\begin{align*}
D_k=
 \sum_{j=1}^J m_{jk} S_{j} = \sum_{j=1}^J n_{jk}\smin_{j}.
\end{align*}

\noindent The maximal number of days of supply based on \(D_k\) is 
\begin{equation*}
n_k=\sum_{j=1}^J n_{jk}.
\end{equation*}

** Example
label:sec:example

   
Consider a patient for who we have recorded four purchase dates,
\(T_1, T_2, T_3, T_4\), on which the patient purchased a drug in two
different strengths, \(S_1=50\) and \(S_2=80\). On the first date, the
patient buys two packages with drug strength \(S_1=50\), the first one
contains 15 pills and the other one contains 10 pills, and also one
package with 15 pills of drug strength \(S_2=80\). This means that
\begin{align*}
m_{1,1} = 15 + 10 = 25, \qquad m_{2, 1} = 15.
\end{align*}
We let the minimal doses corresponding to \(S_1, S_2\) be \(\smin_1 =
25\) and \( \smin_2 = 20\). This gives
\begin{align*}
n_{1, 1} = 25 \cdot \frac{50}{25} = 50, \qquad 
n_{2, 1} = 15 \cdot \frac{80}{20} = 60. 
\end{align*}
Thus, the total amount of drug purchased on date \(T_1\) is,
\begin{align*}
D_1 = 50\cdot 25 + 60\cdot 20 = 2450,
\end{align*}
and the maximal number of days of supply is \(n_1 = 50 + 60=110 \).\\

\noindent We put the date on a form appropriate for the implemented software.

#+name: ex1
#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R :exports output :results output raw drawer  :session *R* :cache yes 
org(d$drugdb)
#+END_SRC

#+RESULTS[<2016-11-21 12:14:53> 7f757f04e0718963a611b1da281aa28ef142f9c5]:
:RESULTS:
|    | id | atc |      pdate | strength | npack | ppp |
|----+----+-----+------------+----------+-------+-----|
|  1 |  1 | A07 | 2012-05-08 |       50 |    10 |   1 |
|  2 |  1 | A07 | 2012-05-08 |       50 |    15 |   1 |
|  3 |  1 | A07 | 2012-05-08 |       80 |    10 |   1 |
|  4 |  1 | A07 | 2012-08-11 |       50 |    15 |   1 |
|  5 |  1 | A07 | 2013-03-15 |       50 |    10 |   1 |
|  6 |  1 | A07 | 2013-03-15 |       50 |    10 |   2 |
|  7 |  1 | A07 | 2013-05-05 |       80 |    10 |   1 |
|  8 |  1 | A07 | 2013-05-25 |       80 |    15 |   3 |
|  9 |  1 | A07 | 2013-10-01 |       50 |    10 |   2 |
| 10 |  1 | A07 | 2013-10-01 |       80 |    10 |   1 |
| 11 |  1 | A07 | 2013-12-28 |       80 |    10 |   1 |
:END:

\noindent We illustrate how the data is preprocessed according to Section
ref:sec:prescription. In the table below, we have the unique list of
dates, \verb+B+, the total doses, \verb+D+, and the days of supply,
\verb+nk+.

#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R :exports output :results output raw drawer  :session *R* :cache yes 
org(ex$exdrug[, names(ex$exdrug) %in% c("B", "D", "nk")])
#+END_SRC

#+RESULTS[<2016-11-21 12:15:00> 3875a0561d85f2b75cbade99e635fd0eaab329ed]:
:RESULTS:
|   |          B |    D |  nk |
|---+------------+------+-----|
| 1 | 2012-05-08 | 2050 |  90 |
| 2 | 2012-08-11 |  750 |  30 |
| 3 | 2013-03-15 | 1500 |  60 |
| 4 | 2013-05-05 |  800 |  40 |
| 5 | 2013-05-25 | 3600 | 180 |
| 6 | 2013-10-01 | 1800 |  80 |
| 7 | 2013-12-28 |  800 |  40 |
:END:






* Hospital admission data
label:sec:hospital

Hospitals usually deliver drugs for their patients. It therefore seems
reasonable to take into account periods of hospitalization in the
calculation of exposure lengths. For a single patient we define up to
\(Q\) periods of hospitalization by the admission dates ${L}_1,\ldots,
{L}_{{Q}}$ and the corresponding discharge dates ${R}_1,\ldots,
{R}_{{Q}}$. We compute the number of days a patient is not
hospitalized in the period \(\periodK\) as:
\begin{align*}
H_k &= \left({T}_{k+1} - {T}_{k}\right) - \sum_{q=1}^{{Q}} \max \big( 0,\,\min \left({T}_{k+1},{R}_{q}\right) - \max\left({T}_{k}, {L}_{q}\right)\big)
\end{align*}

** Example (continued)
We consider again the patient of the example in section
ref:sec:example and now also assume that the patient was hospitalized two times
(Figure ref:fig:ex1).

#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R :exports output :results output raw drawer  :session *R* :cache yes 
org(d$admdb)
#+END_SRC

#+RESULTS[<2016-11-21 12:15:08> 0e2466d1b0df902fc7e8272acbb697f5cca0bc6b]:
:RESULTS:
|   | id |     inddto |      uddto |
|---+----+------------+------------|
| 1 |  1 | 2012-06-11 | 2012-06-28 |
| 2 |  1 | 2013-01-03 | 2013-01-18 |
:END:

\noindent We compute the number of days hospitalized, \verb+DH+, and the number
of days non-hospitalized, \verb+H+.

#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R :exports output :results output raw drawer  :session *R* :cache yes 
org(ex$exdrug[, names(ex$exdrug) %in% c("B", "DH", "H")])
#+END_SRC

#+RESULTS[<2016-11-21 12:15:13> a71bb2b15728ab0d2e873ee6a39fe53466461046]:
:RESULTS:
|   |          B |   H | DH |
|---+------------+-----+----|
| 1 | 2012-05-08 |  78 | 17 |
| 2 | 2012-08-11 | 201 | 15 |
| 3 | 2013-03-15 |  51 |  0 |
| 4 | 2013-05-05 |  20 |  0 |
| 5 | 2013-05-25 | 129 |  0 |
| 6 | 2013-10-01 |  88 |  0 |
| 7 | 2013-12-28 |   1 |  0 |
:END:




#+BEGIN_SRC R :results graphics :file "./drug-dat1b.pdf" :exports none  :session *R* :width 15 :height 3
plot(d)
#+END_SRC

#+RESULTS:
[[file:./drug-dat1b.pdf]]

#+LABEL: fig:ex1
#+ATTR_LATEX: :width 0.8 \textwidth
#+CAPTION: Illustration of the four prescription dates and the two periods of hospitalization of our example patient. 
[[file:./drug-dat1b.pdf]]




* Exposure strength and exposure lengths

The aim is to estimate the ends of the exposure periods \(E_k\) and
for each exposure period to estimate the exposure strength per day
\(X_k\). It is important to note that the estimates are only based on
the data of the current patient and on specific assumptions
which may or may not be valid for a given patient and a given drug.
The estimates are based on the drug prescription data (Section
ref:sec:prescription) and the hospitalization dates (Section
ref:sec:hospital) and depend further on an integer \(\lag\) that
defines the number of prescription dates back in time to use in the
calculations of exposure in a given period \periodK.

** Remark
The original SAS macro also uses prescription dates in the future to
estimate the current exposure strength. However, since usually the aim
is to use the exposure in Poisson and Cox regression where this would
violate the mathematical framework the authors of this report hesitate
to implement this feature. To motivate the feature we would very much
like to see an example which demonstrates that the results of the Cox
or Poisson regression can be improved when estimates of the current
exposure depend on future purchases of the drug.

** Definition of periods included in the estimates

To express the exposure in period \(\periodK\) recall from section
ref:sec:prescription that based on the total drug purchase on date
\(T_k\) the patient can be exposed at most \(n_k=\sum_{j=1}^J n_{jk}\)
days. We use the following notation to define potential overlap, i.e., to
indicate if the maximal number of exposure days exceeds the number of
non-hospitalized days in period \periodK:
\begin{align*} 
u_{k} = \begin{cases}
0, & n_{k} \le H_k,\,\,   \text{in words:  \it the supply at \(T_k\) is empty before \(T_{k+1}\)}\\
1, & n_{k} > H_k,\,\, \text{in words: \it the supply at \(T_k\) can be sufficient to reach \(T_{k+1}\)}.
\end{cases}
\end{align*}

*** Example (continued)

Figure ref:fig:ex2 shows again the data of section ref:sec:example,
together with an illustration of the number of days of supply. The
black lines show the actual days of medicin supply, and the red lines
are the days hospitalized. 

#+BEGIN_SRC R :results graphics :file "./drug-dat2b.pdf" :exports none  :session *R* :width 14 :height 7
plotoutput(ex, which=1)
#+END_SRC

#+RESULTS:
[[file:./drug-dat2b.pdf]]

#+LABEL: fig:ex2
#+ATTR_LATEX: :width 0.8 \textwidth
#+CAPTION: For our example patient the figures shows the maximal number of days of supply calculated at each time point based on the formula in Section  ref:sec:prescription.
[[file:./drug-dat2b.pdf]]



\noindent A first preliminary version of the average dosis per day in period
\(\periodK\) is calculated as
\begin{equation*}
 A_{k}= \frac{1}{c_{k}}  \sum_{j=1}^J G_{jk} \, S_{j}
\end{equation*}
where \(c_k = \sum_{j=1} ^J G_{jk}\) is the total number of purchases
on date \(T_k\). \\

\noindent Since the preliminary average \(A_{k}\) may lie between two of the available
drug strengths we define a second, still preliminary, version of the
average dosis per day as the nearest drug strengths which does not
exceed the average strength. That is, the index
\begin{align}\label{indexj}
b(k) &= \max \left\lbrace j \in \lbrace 1, \ldots, J\rbrace \, :\,  S_j \le  A_{k} \right\rbrace
\end{align}
identifies the nearest drug strength which does not exceed the first
preliminary average strength, and \(S_{b(k)}\) is nearest drug
strength. 


*** Example (continued)

For the patient of our example we have
\begin{align*}
A_1 = \frac{1}{2+1} \left(2\cdot 50 + 80 \right) =  60.
\end{align*}

\noindent We see that \(b(1) = 1\), as \(S_1=50\) is the nearest drug strength
not exceeding the average of \(A_1=60 \) computed above. Note that in
this notation, \(S_{b(k-1)}\) refers to the nearest drug strength of
the previous prescription date. For instance, at date \(T_2\) of our
patient we have \(b(k-1)=b(1)= 1\) and \(S_{b(k-1)} = 50\). \\


\noindent  On the following still quite long remaining part of the pilgrim trail
towards the final estimate of the average daily dosis in period
\(\periodK\), the next thing to do is to decide how many purchase
dates back in time should be used. We distinguish between two cases
which are also illustrated in Figure ref:fig:periods. Which case to be
used will be made clear later.\\

#+BEGIN_SRC R :results graphics :file "./drug-dat2a.pdf" :exports none  :session *R* :width 10 :height 4
if (system("echo $USER",intern=TRUE)=="tag"){
    setwd("~/research/SoftWare/heaven/worg/")
} else{
    setwd("~/research/Software/medicin-macro/heaven/worg/")
}
par(mar=c(3.1,3.1,3.1,3.1))
plot(0,0,type="n",xlim=c(0,100),ylim=c(0,100),xlab="Calendar time",ylab="", 
     yaxt='n', xaxt='n', axes=FALSE)

## set.seed(9)
## vt <- sort(round(sample(100, 5)/5)*5)
vt <- c(5,20,35,55,75,100)
axis(1,at=vt,labels=c(expression(T[k-5]),expression(T[k-4]),expression(T[k-3]),expression(T[k-2]),expression(T[k-1]),expression(T[k])))
axis(1,at=seq(0,100,by = 5),labels=rep(NA, 21))
abline(v = vt, lty=2)
vtype <- c(25, 75)
## axis(4, at=vtype, labels=c(expression(I[k]^(2)), expression(I[k]^(1))),
## las=2, cex.axis=1.1, tck=0.0, lwd=0)
axis(4, at=vtype, labels=paste("Case",2:1),
     las=2, cex.axis=1.1, tck=0.0, lwd=0,line=-1,xpd=NA)
spoints <- function(a,b,pos,col,cex,lwd){
    points(seq(a,b,5),rep(pos,length(seq(a,b,5))),pch=19,cex=cex,col=col)
    segments(x0=a,x1=b,y0=pos,y1=pos,lwd=lwd,col=col)
}
##--- for case 1
spoints(a=vt[1],b=vt[2]-10,pos=vtype[2],cex=2.3,col="black",lwd=2)
spoints(a=vt[2],b=vt[3],pos=vtype[2],cex=1.3,col="black",lwd=1)
spoints(a=vt[3],b=vt[4],pos=vtype[2],cex=1.3,col="black",lwd=1)
spoints(a=vt[4],b=vt[6],pos=vtype[2],cex=2.3,col="red",lwd=2)
##--- for case 2
spoints(a=vt[1],b=vt[2],pos=vtype[1],cex=2.3,col="black",lwd=2)
spoints(a=vt[2],b=vt[3]-5,pos=vtype[1],cex=1.3,col="black",lwd=1)
## spoints(a=vt[3],b=vt[4],pos=vtype[1],cex=1.3,col="black",lwd=1)
spoints(a=vt[3],b=vt[6],pos=vtype[1],cex=1.3,col="red",lwd=2)
#+END_SRC

#+RESULTS:
[[file:./drug-dat2a.pdf]]


#+LABEL: fig:periods
#+ATTR_LATEX: :width 0.8 \textwidth
#+CAPTION: Illustration of the periods back in time to include into the final estimate of the average daily dosis at \(T_k\). Shown are two independent examples illustrating case 1 and case 2, respectively. The size of the dots indicates the preliminary average strength. The red periods are included in the final estimate of the average daily dosis in period \periodK. See also Figure ref:fig:cases.
[[file:./drug-dat2a.pdf]]


# Which case to be used is determined by Figure  ref:fig:cases: case (I) in  Figure ref:fig:cases corresponds to case 1  and case (II) in  Figure ref:fig:cases corresponds to case 2.

\noindent *Case 1*: \it \(T_{ {I}^{(1)}_{k}}\) \it is the closest purchase
date back in time, such that there is both continuous potential
overlap and average dosis match. The index is defined as\rm
\begin{align*}
 {I}^{(1)}_{k} = &\max \big( \min \lbrace \ell\in \lbrace \max(1,k-N), \ldots, k-1\rbrace \, :\, u_\ell = \cdots =
 u_{k-1} =1 \rbrace, \\
  &\min \lbrace \ell\in \lbrace \max(1,k-N), \ldots, k\rbrace \,:\, B_{\ell} = \cdots = B_{k}  \rbrace \big),
\intertext{\it The average daily dose in the period \([T_{ {I}^{(1)}_{k}}, T_{k+1})\) is defined as}
 M^{(1)}_k =   &\frac{ \sum_{\ell= I^{(1)}_k}^{k-1} \, D_\ell}{ \sum_{\ell= I^{(1)}_k}^{k-1} \, H_\ell}.
\intertext{\bf{Case 2}: \(T_{ {I}^{(2)}_{k}}\) \it is the closest purchase date back in time, such that there is
  \it continuous potential overlap. The index is defined as}
{I}^{(2)}_{k} =  &\min \lbrace \ell\in \lbrace \max(1,k-N), \ldots, k-1\rbrace\, : \,u_\ell = \cdots = u_{k-1} =1 \rbrace.
\intertext{\it The average daily dose in the period \([T_{ {I}^{(2)}_{k}}, T_{k+1})\) is defined as}
 M^{(2)}_k =   &\frac{ \sum_{\ell= I^{(2)}_k}^{k-1} \, D_\ell}{ \sum_{\ell= I^{(2)}_k}^{k-1} \, H_\ell}.
\end{align*}

\noindent At last, we define the rounding of the average daily dose
\(M^{(1)}_k\) to the nearest multiple of the minimal dose
\(\smin_{b(k)}\) (the index \(b(k)\) defined in
equation eqref:indexj) smaller than the average dose, that is
\begin{equation*}
W_k= \left\lfloor \frac{M_k^{(1)}}{\smin_{b(k)}} \right \rfloor \smin_{b(k)}.
\end{equation*}

*** Example (continued)


Figure  ref:fig:ex3 shows the periods to be used in the calculations for our example patient. 

#+BEGIN_SRC R :results graphics :file "./drug-dat2c.pdf" :exports none  :session *R* :width 10 :height 5
plotoutput(ex)
#+END_SRC

#+RESULTS:
[[file:./drug-dat2c.pdf]]

#+LABEL: fig:ex3
#+ATTR_LATEX: :width 0.8 \textwidth
#+CAPTION: The cases for our patient. 
[[file:./drug-dat2c.pdf]]





*** Final estimate of the daily dosis
label:sec:final

The final estimate of the average daily dosis \(X_k\) per day in
period \(\periodK\) is computed as follows, the computations are
illustrated in Figure ref:fig:cases.
\begin{align} 
          &{X}_{k} =  (1-u_{k-1}) \, \styp_{b(k)}\tag{No overlap}\\
	  &+ \, u_{k-1} \bigg[\tag{Overlap}
          \\ & \qquad  1\{S_{b(k-1)}=S_{b(k)}\} W_k \tag{I}
	  \\
\begin{split}
 & \qquad +  1\{S_{b(k-1)}\neq S_{b(k)}\}\bigg( \one \left\lbrace M^{(2)}_k > \smax_{b(k)}\right\rbrace \smax_{b(k)}
\\ & \qquad + \one \left\lbrace M^{(2)}_k > \smin_{b(k)}\right\rbrace \smin_{b(k)} 
\\& \qquad + \one \left\lbrace M^{(2)}_k \le \smax_{b(k)}\right\rbrace \one \left\lbrace M^{(2)}_k \ge \smin_{b(k)}\right\rbrace \styp_{b(k)}\bigg) \bigg].
\end{split}\tag{II}
\end{align}

*** Example (continued)

#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R :exports output :results output raw drawer  :session *R* :cache yes 
org(ex$exdrug[, names(ex$exdrug) %in% c("B", "S", "Sjk", "M", "X")])
#+END_SRC

#+RESULTS[<2016-11-21 13:45:01> d59c21814c7ba951aa4cfba47c930a773a0dc07d]:
:RESULTS:
|   |  X |          B |        M |  S | Sjk |
|---+----+------------+----------+----+-----|
| 1 | 50 | 2012-05-08 | 50.00000 | 60 |  50 |
| 2 | 25 | 2012-08-11 | 26.28205 | 50 |  50 |
| 3 | 50 | 2013-03-15 | 50.00000 | 50 |  50 |
| 4 | 60 | 2013-05-05 | 29.41176 | 80 |  80 |
| 5 | 40 | 2013-05-25 | 40.00000 | 80 |  80 |
| 6 | 50 | 2013-10-01 | 29.50000 | 65 |  50 |
| 7 | 60 | 2013-12-28 | 60.00000 | 80 |  80 |
:END:

FIXME: læs her!!!!
We now suppose that our example patient made only one drug purchase on
the second date \(T_2\), where he bought a package wit 10 pills of
drug strength \(S_1\). We have already shown that \(S_{b(1)} = 50\),
and also get \(S_{b(2)} = 50\). This means that \(S_{b(2)} =
S_{b(1)}\). Figure ref:fig:ex2 shows that \(u_1 =1\), i.e., the
maximal number of days of supply exceed the period from \(T_1\) to
\(T_2\). Hence, we are in case (I) of ref:fig:cases and calculate
\(X_2\) as
\begin{align*}
M_2^{(1)} = \frac{D_1}{H_1} = \frac{1700}{98} \approx 17.35.
\end{align*}
This value is rounded to the nearest multiple of the minimal
corresponding dosis \(\smin_{b(2)} = 25\) and hence \(X_2 = W_2 =
1\cdot \smin_{b(2)} = 25\). \\

\noindent *Remark*: Note that the original SAS macro (even under the left-only option) also
conditioned on the dosis at time \(T_{k+1}\) but that we do not want
to condition on the future until we are convinced by means of real
examples that the potential damage (the mathematics of the Cox and
Poisson regression are violated) can be counterbalanced by potential
benefit.

#+BEGIN_SRC R :results graphics :file "./drug-dat1a.pdf" :exports none :session *R* :width 10 :height 4
if (system("echo $USER",intern=TRUE)=="tag"){
    setwd("~/research/SoftWare/heaven/worg/")
} else{
    setwd("~/research/Software/medicin-macro/heaven/worg/")
}
par(mar=c(3.1,3.1,3.1,8.1))
plot(0,0,type="n",xlim=c(30,100),ylim=c(0,100),xlab="Calendar time",ylab="", 
     yaxt='n', xaxt='n', axes=FALSE)
vt <- c(35, 80)
axis(1, at=vt, labels=c(expression(T[k-1]), expression(T[k])))
axis(1, at=seq(0, 100, by = 5), labels=rep(NA, 21))
vtype <- 100-seq(0, 100, length = 8)[c(2, 3, 5, 7)]
axis(4, at=vtype, labels=c("(no", "overlap)", "(I)", "(II)"),
     las=2, cex.axis=1.1, tck=0.0, lwd=0)
abline(v = vt[1], lty=2)
abline(v = vt[2], lty=2)
spoints <- function(a,b,pos,col,cex,lwd){
    points(seq(a,b,5),rep(pos,length(seq(a,b,5))),pch=19,cex=cex,col=col)
    segments(x0=a,x1=b,y0=pos,y1=pos,lwd=lwd,col=col)
}
##--- for case 1a
spoints(a=vt[1],b=vt[2]-10,pos=vtype[1],cex=1.3,col="black",lwd=2)
spoints(a=vt[2],b=vt[2]+15,pos=vtype[1],cex=2.3,col="black",lwd=2)
##--- for case 1b
spoints(a=vt[1],b=vt[2]-20,pos=vtype[2],cex=1.3,col="black",lwd=2)
spoints(a=vt[2],b=vt[2]+15,pos=vtype[2],cex=1.3,col="black",lwd=2)
##--- for case 2
spoints(a=vt[1],b=vt[2]+15,pos=vtype[3],cex=1.3,col="black",lwd=2)
##--- for case 3
spoints(a=vt[1],b=vt[2],pos=vtype[4],cex=1.3,col="black",lwd=2)
spoints(a=vt[2],b=vt[2]+15,pos=vtype[4],cex=2.3,col="black",lwd=2)
#+END_SRC

#+RESULTS:
[[file:./drug-dat1a.pdf]]

#+LABEL: fig:cases
#+ATTR_LATEX: :width 0.8 \textwidth
#+CAPTION: Illustration of the formula for the final estimate of the daily dosis (section ref:sec:final). The size of the dots indicates the preliminary average strength S_{b(k)}. The upper most two lines illustrate the cases without overlap and the other two lines the cases with overlap.
[[file:./drug-dat1a.pdf]]


*** Calculating the leftover doses, ${R}_1,\ldots, {R}_{k}$

\begin{align*}
{R}_{k} = u_{k-1} \cdot \min \Big[ \text{maxdepot}, \, \max \Big\lbrace 0, \, D_{k-1} + {R}_{k-1} - {X}_{k-1} \Big( {E}_{k-1} - {T}_{k-1}  -\\
 \sum_{q=1}^{{Q}} \max \big( 0,\,\min \left({T}_{k+1},{R}_{q}\right) - \max\left({T}_{k}, {L}_{q}\right)\big) \Big)\Big\rbrace\Big],
\end{align*}

where maxdepot is some user-specified maximum amount of dosis to be ``stored'' from one prescription date to the next, and 
\begin{align*}
 \sum_{q=1}^{{Q}} \max \big( 0,\,\min \left({T}_{k+1},{R}_{q}\right) - \max\left({T}_{k}, {L}_{q}\right)\big)
\end{align*}
is again the number of hospitalized days in the period.


*** Calculating the dates of end of exposure, ${E}_1,\ldots, {E}_{k}$

Note that since \(D_k + R_k\) is the total prescription dose at
\(T_k\) and \(X_k\) is the estimated dose per day the result of
\(\frac{D_{k} + {R}_{k}}{{X}_{k}}\) has days as unit. However, the
result is not necessarily an integer. Therefore, in the following,
\(\lfloor x \rfloor\) denotes the largest integer value not exceeding
\(x\), i.e., the rounded value. The estimated end of the exposure
period in which the daily dose is estimated as \(X_k\) is,
\begin{align*}
{E}_{k}= \min \bigg({T}_{k+1}-1, \, {T}_{k} - 1+  \left\lfloor \frac{D_{k} + {R}_{k}}{{X}_{k}} \right\rfloor\bigg).
\end{align*}

* User interface

work in progress

#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R :exports both :results output raw drawer  :session *R* :cache yes 
library(Publish)
library(heaven)
set.seed(18)
org(simPrescriptionData(1))
#+END_SRC

#+RESULTS[<2016-11-21 13:45:01> e941c7b891ba0b6422b85eec5f5347c9dc3a4080]:
:RESULTS:
| pnr | atc  |       eksd | strnum | packsize | apk |
|-----+------+------------+--------+----------+-----|
|   1 | A07  | 1995-01-01 |    400 |       30 |   1 |
|   1 | A07  | 1995-03-17 |    200 |      300 |   3 |
|   1 | A07  | 1995-06-18 |    400 |       30 |   3 |
|   1 | A07  | 1995-08-06 |    500 |       30 |   1 |
|   1 | A07  | 1996-07-15 |    200 |       60 |   2 |
|   1 | A07  | 1997-08-17 |    200 |      300 |   1 |
|   1 | A07  | 1998-03-20 |    400 |       30 |   1 |
|   1 | A07  | 1999-09-11 |    400 |      100 |   3 |
|   1 | A07  | 1999-12-17 |    200 |       60 |   1 |
|   1 | A12B | 1995-02-16 |    750 |      500 |   2 |
|   1 | A12B | 1995-09-23 |     75 |      250 |   1 |
|   1 | A12B | 1996-05-04 |    750 |      250 |   1 |
:END:

#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R :exports both :results output raw drawer  :session *R* :cache yes 
set.seed(18)
org(simAdmissionData(1))
#+END_SRC

#+RESULTS[<2016-11-21 13:45:01> aad6f2c9c03990d61e630b28b5478151a7ca6a1a]:
:RESULTS:
| pnr |     inddto |      uddto |
|-----+------------+------------|
|   1 | 1996-01-27 | 1996-02-06 |
|   1 | 1996-07-28 | 1996-08-13 |
|   1 | 2006-07-02 | 2006-07-31 |
|   1 | 2009-03-16 | 2009-04-02 |
|   1 | 2014-04-26 | 2014-05-19 |
:END:


#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R  :results output raw drawer  :exports code  :session *R* :cache yes 
d <- dpp()
set.seed(18)
recept_data <- simPrescriptionData(1) 
datoer <- simAdmissionData(1)
drug(d, "drug1") <- atc("A12B")
## drug(d, "drug2", add=TRUE) <- atc("ATC7")
drug(d, A12B) <- pack(c(50, 75, 100, 125), 
                               min = c(10, 50, 25, 50), 
                               max = c(75, 200, 150, 150), 
                               def = c(50, 100, 100, 125))
drugdb(d, add=FALSE, id=pnr) <- recept_data
admdb(d) <- datoer
period(d) <- as.Date(c("1995-01-01", "2015-05-01"))
N(d) <- 2
d
#+END_SRC

#+RESULTS[<2016-11-21 13:45:01> 272e4cee8f6e9b86aa56a9ff64b227416075a532]:
:RESULTS:
preprocessing object 
----------------- 

Calculations for treatment(s): 
 "drug1": A12B 
 A12B:  

Dose values to be used in calculations: 
       value min max def
A12B.1    50  10  75  50
A12B.2    75  50 200 100
A12B.3   100  25 150 100
A12B.4   125  50 150 125

Doses found in data and not in the above: 
 "drug1": 750, 75 
 A12B:  
 

Using N = 2 prescriptions back in time 
Only interested in prescriptions between 1995-01-01 and 2015-05-01
:END:


** COMMENT Output

The output consists of:

-  ${B}_1, \ldots, B_{{K}}$: Starting dates for each prescription
   period.
-  ${E}_1, \ldots, E_{{K}}$: End dates for each prescription period.
-  ${X}_1, \ldots, {X}_{{K}}$: Calculated dose for each prescription
   period.


* HEADER :noexport:

#+TITLE: From \texttt{\%x\_recepter} to \texttt{Rcpp}: a mathematical formulation of the algorithm, a new R-user interface and an efficient implementation
#+AUTHOR: Helene Charlotte Rytgaard and Thomas Alexander Gerds 
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:t todo:t pri:nil tags:not-in-toc author:t
#+LaTeX_CLASS: org-article
#+LaTeX_HEADER:\usepackage{authblk}
# #+LaTeX_HEADER:\author{Helene Charlotte Rytgaard and Thomas Alexander Gerds}
#+LaTeX_HEADER:\newcommand{\EE}{\mathbb{E}}
#+LaTeX_HEADER:\newcommand{\one}{1}
#+LaTeX_HEADER:\newcommand{\VV}{\mathbb{V}}
#+LaTeX_HEADER:\newcommand{\PP}{\mbox{P}}
#+LaTeX_HEADER:\newcommand{\norm}{\mathcal{N}}
#+LaTeX_HEADER:\newcommand{\lag}{N}
#+LaTeX_HEADER:\newcommand{\str}{S}
#+LaTeX_HEADER:\newcommand{\smin}{s^{\min}}
#+LaTeX_HEADER:\newcommand{\smax}{s^{\max}}
#+LaTeX_HEADER:\newcommand{\styp}{s^{*}}
#+LaTeX_HEADER:\newcommand{\period}{[a,b]}
#+LaTeX_HEADER:\newcommand{\periodK}{\ensuremath{[T_k,T_{k+1})}}
#+LaTeX_HEADER:\newcommand{\K}{K}
#+LaTeX_HEADER:\newcommand{\kk}{k}
#+LaTeX_HEADER:\newcommand{\D}{D}
#+LaTeX_HEADER:\newcommand{\B}{B}
#+LaTeX_HEADER:\newcommand{\E}{E}
#+LaTeX_HEADER:\newcommand{\XX}{X}
#+LaTeX_HEADER:\newcommand{\LL}{L}
#+LaTeX_HEADER:\newcommand{\QQ}{Q}
#+LaTeX_HEADER:\newcommand{\Ru}{R}
#+LaTeX_HEADER:\newcommand{\GG}{G}
#+LaTeX_HEADER:\newcommand{\T}{T}
#+LaTeX_HEADER:\newcommand{\st}{s}
#+LaTeX_HEADER:\newcommand{\Nn}{N}
#+LaTeX_HEADER:\newcommand{\A}{A}
#+LaTeX_HEADER:\newcommand{\C}{C}
#+LaTeX_HEADER:\newcommand{\uu}{u}
#+LaTeX_HEADER:\newcommand{\vv}{v}
#+LaTeX_HEADER:\newcommand{\zz}{z}
#+LaTeX_HEADER:\newcommand{\ww}{w}
#+LaTeX_HEADER:\newcommand{\M}{M}
#+LaTeX_HEADER:\newcommand{\I}{I}
#+LaTeX_HEADER:\newcommand{\RR}{R}
# #+LaTeX_HEADER:\affil{Department of Biostatistics, University of Copenhagen, Copenhagen, Denmark}
#+PROPERTY: header-args session *R*
#+PROPERTY: header-args cache yes

