* Introduction

The Danish National Prescription Registry (NCBI) provides
patient-level data on all prescription drugs sold in Danish
community pharmacies since 1994 citep:kildemoes2011danish. Effects and
side effects of drugs can be assessed in a Danish nation wide registry
study. For this the prescription data are linked to the cause of death
register and other Danish registries citep:thygesen2011introduction.

This document describes the /medicin macro/ by Christian
Torp-Pedersen, a complex algorithm for the computation of drug
exposure strength and length relative to a prespecified study period
$\period$ in calendar time. Note that the start of the study period has to be after the
start of the registry in 1994.




* Drug prescription data
label:sec:prescription

We describe the data of a single person who has purchased the drug of
interest at ${K}$ different dates in the study period \period. The
setup can easily be generalized to multiple patients. The set of
ordered drug purchase dates for one patient is denoted as
\begin{equation*}
{T}_1< \cdots< {T}_{K}.
\end{equation*}
Here \(K\) is the number of times the patient has purchased one or
more packages of the same drug product in the period \(\period\). One
package of each drug product is defined by the drug strength 
of the smallest unit (e.g., one pill or half a pill) and the amount of
such units that it contains. For each drug product we distinguish \(J\ge 1\)
different package types according to the different strengths: 
\begin{equation*}
\str_1 <\dots< \str_J.
\end{equation*}
Note that the original SAS macro allowed at most 4 different package
types but that the new implementation does not have this
limitation. For each drug strength \(\str_j\), the values \(\smin_j\),
\(\smax_j\), \(\styp_j\) define the minimal, maximal and typical dose
per day, respectively. 

We now describe the total amount of drug purchased on date \(T_k\) and
the corresponding maximal number of days of supply. First, note that
since \(\smin_j\) is the minimal dosis, one unit of strength
\(\str_j\) can supply a maximal number of \((\str_j/\smin_j)\)
days. Next, consider that on date \(T_k\) the patient purchases
\(G_{jk}\) many packages of strength \(\str_j\). If the patients
purchases no package of strength j on date \(T_k\) then
\(G_{jk}=0\). Since each package may include a different number of
units, the total amount of units of strength \(\str_j\) purchased on date
\(T_k\) is given by
\begin{equation*}
m_{jk}=\sum_{g=1}^{G_{jk}}\text{(number of units in package \(g\))}
\end{equation*}
We convert this number to the scale defined by smallest units and
define the total amount of smallest units of strength \(\str_j\)
purchased on date \(T_k\) as
\begin{equation*}
n_{jk} = m_{jk} \frac{\str_j}{\smin_j}.
\end{equation*}
The total amount \(D_k\) of the drug purchased on date \(T_k\) is
given by the formula
\begin{align*}
D_k=
 \sum_{j=1}^J m_{jk} S_{j} = \sum_{j=1}^J n_{jk}\smin_{j}.
\end{align*}
The maximal number of days of supply based on \(D_k\) is 
\(n_k=\sum_{j=1}^J n_{jk}\).\\

Let us consider a small example of an individual \(y\) with four
purchase dates, \(T_1, T_2, T_3, T_4\), and a drug ``z'' with two
different strengths, \(S_1=50\) and \(S_2=80\). On the first date, individual \(y
\) buys two packages with drug strength \(S_1\), the first one with 15
units and the other with 10 units, and one package with
drug strength \(S_2\) and  10 units. This means that
\begin{align*}
m_{1,1} = 15 + 10 = 25, \qquad m_{2, 1} = 10.
\end{align*}
We let the minimal doses corresponding to \(S_1, S_2\) be \(\smin_1 = 10, \smin_2 = 20\), such that 
\begin{align*}
n_{1, 1} = 25 \cdot \tfrac{50}{10} = 125, \qquad 
n_{2, 1} = 10 \cdot \tfrac{80}{20} = 40. 
\end{align*}
Thus, the total amount of drug purchased on date \(T_1\) is, 
\begin{align*}
D_1 = 125\cdot 10 + 40\cdot 20 = 2050,
\end{align*}
and the maximal number of days of supply is \(n_1 = 125 + 40=165 \).

 

* Hospital admission data
label:sec:hospital

Hospitals usually deliver drugs for their patients. It therefore seems
reasonable to take into account periods of hospitalization in the
calculation of exposure lengths. For a single patient we define up to
\(Q\) periods of hospitalization by the admission dates ${L}_1,\ldots,
{L}_{{Q}}$ and the corresponding discharge dates ${R}_1,\ldots,
{R}_{{Q}}$. We compute the number of days a patient is not
hospitalized in the period \(\periodK\) as:
\begin{align*}
H_k &= \left({T}_{k+1} - {T}_{k}\right) - \sum_{q=1}^{{Q}} \max \big( 0,\,\min \left({T}_{k+1},{R}_{q}\right) - \max\left({T}_{k}, {L}_{q}\right)\big)
\end{align*}

We consider again individual \(y \) from the previous section. Let us
say that \(y\) was hospitalized twice. 


#+BEGIN_SRC R :results graphics :file "./drug-dat1b.pdf" :exports results  :session *R* :width 15 :height 4
if (system("echo $USER",intern=TRUE)=="tag"){
    setwd("~/research/SoftWare/heaven/worg/")
} else{
    setwd("~/research/Software/medicin-macro/heaven/worg/")
}
par(mar=c(3.1,3.1,3.1,3.1))

T <- c("2012-05-08", "2012-11-11", "2012-12-01", "2013-01-05")

## set.seed(9)
## vt <- sort(round(sample(100, 5)/5)*5)
vt <- sapply(T, as.Date)

plot(0,0,type="n",xlim=c(vt[1]-10,vt[4]+10),ylim=c(0,100),xlab="Calendar time",ylab="", 
     yaxt='n', xaxt='n', axes=FALSE)
#title(main="Case II")

axis(1, at=vt, labels=T, las=2)
#+END_SRC

#+LABEL: fig:periods
#+ATTR_LATEX: :width 0.8 \textwidth
#+CAPTION: Illustration of the periods back in time to include into the estimate of the average daily dosis. The size of the dots indicates the second preliminary average strength B_{k}. The red periods are included in two cases of the estimate of the average daily dosis in period \periodK. Which case to be used is determined by the cases in Figure  ref:fig:cases, such that case (II) in  Figure ref:fig:cases uses case 1 and case (III) in  Figure ref:fig:cases uses case 2.
#+RESULTS:
[[file:./drug-dat1b.pdf]]


FIXME: 
- what if L_q <a eller R_q>b? limit to the study period \period?
- should the day \(T_{k+1}\) be included [T_k, T_{k+1}] or not \periodK?

* Exposure strength and exposure lengths

The aim is to estimate the ends of the exposure periods \(E_k\) and
for each exposure period to estimate the exposure strength per day
\(X_k\). It is important to note that the estimates are only based on
the data of the current patient and based on specific assumptions
which may or may not be valid for a given patient and a given drug.
The estimates are based on the drug prescription data (Section
ref:sec:prescription) and the hospitalization dates (Section
ref:sec:hospital) and depend further on an integer \(\lag\) that
defines the number of prescription dates back in time to use in the
calculations of exposure in a given period \periodK.

** Remark
The original SAS macro also uses prescription dates in the future to
estimate the current exposure strength. However, since usually the aim
is to use the exposure in Poisson and Cox regression where this would
violate the mathematical framework the authors of this report hesitate
to implement this feature. To motivate the feature we would very much
like to see an example which demonstrates that the results of the Cox
or Poisson regression can be improved when estimates of the current
exposure depend on future purchases of the drug.

** Definition of periods included in the estimates

To express the exposure in period \(\periodK\) recall from section
ref:sec:prescription that based on the total drug purchase on date
\(T_k\) the patient can be exposed at most \(n_k=\sum_{j=1}^J n_{jk}\)
days. We use the following notation to define potential overlap, i.e., to
indicate if the maximal number of exposure days exceeds the number of
non-hospitalized days in period \periodK:
\begin{align*} 
u_{k} = \begin{cases}
0, & n_{k} \le H_k,\,\,   \text{in words:  \it the supply at \(T_k\) is empty before \(T_{k+1}\)}\\
1, & n_{k} > H_k,\,\, \text{in words: \it the supply at \(T_k\) can be sufficient to reach \(T_{k+1}\)}.
\end{cases}
\end{align*}

A first preliminary version of the average dosis per day in period
\(\periodK\) is calculated as
\begin{equation*}
 A_{k}= \frac{1}{c_{k}}  \sum_{j=1}^J \one \lbrace n_{jk}>0\rbrace\, S_{j}
\end{equation*}
where \(c_k = \sum_{j=1} ^J  G_{jk}\) is the
number of different drug strengths purchased on date \(T_k\). Since
the preliminary average \(A_{k}\) may lie between two of the available
drug strengths we define a second still preliminary version of the
average dosis per day as the nearest drug strengths which does not
exceed the average strength. That is, the index
\begin{align}\label{indexj}
j(k) &= \max \left\lbrace \ell \in \lbrace 1, \ldots, J\rbrace \, :\,  S_\ell \le  A_{k} \right\rbrace
\end{align}
identifies the nearest drug strength which does not exceed the first
preliminary average strength, and \(S_{j(k)}\) is nearest drug
strength. Note that in this notation, \(S_{j(k-1)}\) refers to the
nearest drug strength of the previous prescription date.  On the
following still quite long remaining part of the pilgrim trail towards
the final estimate of the average daily dosis in period \(\periodK\)
the next thing to do is to decide how many purchase dates back in time
should be used. We distinguish between two cases which are also
illustrated in Figure ref:fig:periods.

#+BEGIN_SRC R :results graphics :file "./drug-dat2a.pdf" :exports results  :session *R* :width 10 :height 4
if (system("echo $USER",intern=TRUE)=="tag"){
    setwd("~/research/SoftWare/heaven/worg/")
} else{
    setwd("~/research/Software/medicin-macro/heaven/worg/")
}
par(mar=c(3.1,3.1,3.1,3.1))
plot(0,0,type="n",xlim=c(0,100),ylim=c(0,100),xlab="Calendar time",ylab="", 
     yaxt='n', xaxt='n', axes=FALSE)
#title(main="Case II")

## set.seed(9)
## vt <- sort(round(sample(100, 5)/5)*5)
vt <- c(5,20,35,55,75,100)

axis(1,at=vt,labels=c(expression(T[k-5]),expression(T[k-4]),expression(T[k-3]),expression(T[k-2]),expression(T[k-1]),expression(T[k])))
axis(1,at=seq(0,100,by = 5),labels=rep(NA, 21))

abline(v = vt, lty=2)

vtype <- c(25, 75)
## axis(4, at=vtype, labels=c(expression(I[k]^(2)), expression(I[k]^(1))),
## las=2, cex.axis=1.1, tck=0.0, lwd=0)
axis(4, at=vtype, labels=paste("Case",2:1),
     las=2, cex.axis=1.1, tck=0.0, lwd=0,line=-1,xpd=NA)
spoints <- function(a,b,pos,col,cex,lwd){
    points(seq(a,b,5),rep(pos,length(seq(a,b,5))),pch=19,cex=cex,col=col)
    segments(x0=a,x1=b,y0=pos,y1=pos,lwd=lwd,col=col)
}
##--- for case 1
spoints(a=vt[1],b=vt[2]-10,pos=vtype[2],cex=2.3,col="black",lwd=2)
spoints(a=vt[2],b=vt[3],pos=vtype[2],cex=1.3,col="black",lwd=1)
spoints(a=vt[3],b=vt[4],pos=vtype[2],cex=1.3,col="black",lwd=1)
spoints(a=vt[4],b=vt[6],pos=vtype[2],cex=2.3,col="red",lwd=2)
##--- for case 2
spoints(a=vt[1],b=vt[2],pos=vtype[1],cex=2.3,col="black",lwd=2)
spoints(a=vt[2],b=vt[3]-5,pos=vtype[1],cex=1.3,col="black",lwd=1)
## spoints(a=vt[3],b=vt[4],pos=vtype[1],cex=1.3,col="black",lwd=1)
spoints(a=vt[3],b=vt[6],pos=vtype[1],cex=1.3,col="red",lwd=2)
#+END_SRC

#+LABEL: fig:periods
#+ATTR_LATEX: :width 0.8 \textwidth
#+CAPTION: Illustration of the periods back in time to include into the estimate of the average daily dosis. The size of the dots indicates the second preliminary average strength B_{k}. The red periods are included in two cases of the estimate of the average daily dosis in period \periodK. Which case to be used is determined by the cases in Figure  ref:fig:cases, such that case (II) in  Figure ref:fig:cases uses case 1 and case (III) in  Figure ref:fig:cases uses case 2.
#+RESULTS:
[[file:./drug-dat2a.pdf]]


\noindent *Case 1* \it \(T_{ {I}^{(1)}_{k}}\) \it is the closest purchase
date back in time, such that there is both continuous potential
overlap and average dosis match. The index is defined as\rm
\begin{align*}
 {I}^{(1)}_{k} = &\max \big( \min \lbrace \ell\in \lbrace \max(1,k-N), \ldots, k-1\rbrace \, :\, u_\ell = \cdots =
 u_{k-1} =1 \rbrace, \\
  &\min \lbrace \ell\in \lbrace \max(1,k-N), \ldots, k\rbrace \,:\, B_{\ell} = \cdots = B_{k}  \rbrace \big),
\intertext{\it The average daily dose in the period \([T_{ {I}^{(1)}_{k}}, T_{k+1})\) is defined as}
 M^{(1)}_k =   &\frac{ \sum_{\ell= I^{(1)}_k}^{k-1} \, D_\ell}{ \sum_{\ell= I^{(1)}_k}^{k-1} \, H_\ell}.
\intertext{\bf{Case 2}: \(T_{ {I}^{(2)}_{k}}\) \it is the closest purchase date back in time, such that there is
  \it continuous potential overlap. The index is defined as}
{I}^{(2)}_{k} =  &\min \lbrace \ell\in \lbrace \max(1,k-N), \ldots, k-1\rbrace\, : \,u_\ell = \cdots = u_{k-1} =1 \rbrace.
\intertext{\it The average daily dose in the period \([T_{ {I}^{(2)}_{k}}, T_{k+1})\) is defined as}
 M^{(2)}_k =   &\frac{ \sum_{\ell= I^{(2)}_k}^{k-1} \, D_\ell}{ \sum_{\ell= I^{(2)}_k}^{k-1} \, H_\ell}.
\end{align*}

At last, we define
the rounding of the average daily dose \( M^{(1)}_k\) to the nearest
multiple of the minimal dose \(\smin_{j(k)}\) which corresponds to
index \(j(k)\) defined in equation eqref:indexj as
\begin{equation*}
W_k=\max \left\lbrace \underset{p \in
\mathbb{N}}{\text{argmin}} \left\vert M^{(1)}_k - p
\smin_{j(k)}\right\vert \smin_{j(k)}\right\rbrace.
\end{equation*}

*** Estimate of the daily dosis

The final estimate of the average daily dosis \(X_k\) per day in
period \(\periodK\) is computed as follows, the computations are
illustrated in Figure ref:fig:cases.
\begin{align} 
          &{X}_{k} =  (1-u_{k-1}) \, \styp_{j(k)}\tag{No overlap}\\
	  &+ \, u_{k-1} 1\{S_{j(k-1)}=S_{j(k)}\}\bigg[\tag{Overlap}
          \\ & \qquad W_k \tag{II}
	  \\
\begin{split}
 & \qquad + \one \left\lbrace M^{(2)}_k > \smax_{j(k)}\right\rbrace \smax_{j(k)} +  \one \left\lbrace M^{(2)}_k > \smin_{j(k)}\right\rbrace \smin_{j(k)}
\\ & \qquad +  \one \left\lbrace M^{(2)}_k \le \smax_{j(k)}\right\rbrace \one \left\lbrace M^{(2)}_k \le \smin_{j(k)}\right\rbrace \styp_{j(k)} \bigg].
\end{split}\tag{III}
\end{align}

\noindent *Remark*: Note that the original SAS macro (even under the left-only option) also
conditioned on the dosis at time \(T_{k+1}\) but that we do not want
to condition on the future until we are convinced by means of real
examples that the potential damage (the mathematics of the Cox and
Poisson regression are violated) can be counterbalanced by potential
benefit.

#+BEGIN_SRC R :results graphics :file "./drug-dat1a.pdf" :exports results :session *R* :width 10 :height 4
if (system("echo $USER",intern=TRUE)=="tag"){
    setwd("~/research/SoftWare/heaven/worg/")
} else{
    setwd("~/research/Software/medicin-macro/heaven/worg/")
}
par(mar=c(3.1,3.1,3.1,3.1))
plot(0,0,type="n",xlim=c(30,100),ylim=c(0,100),xlab="Calendar time",ylab="", 
     yaxt='n', xaxt='n', axes=FALSE)
vt <- c(35, 80)
axis(1, at=vt, labels=c(expression(T[k-1]), expression(T[k])))
axis(1, at=seq(0, 100, by = 5), labels=rep(NA, 21))
vtype <- 100-seq(0, 100, length = 8)[c(2, 3, 5, 7)]
axis(4, at=vtype, labels=c("(Ia)", "(Ib)", "(II)", "(III)"),
     las=2, cex.axis=1.1, tck=0.0, lwd=0)
abline(v = vt[1], lty=2)
abline(v = vt[2], lty=2)
spoints <- function(a,b,pos,col,cex,lwd){
    points(seq(a,b,5),rep(pos,length(seq(a,b,5))),pch=19,cex=cex,col=col)
    segments(x0=a,x1=b,y0=pos,y1=pos,lwd=lwd,col=col)
}
##--- for case 1a
spoints(a=vt[1],b=vt[2]-10,pos=vtype[1],cex=1.3,col="black",lwd=2)
spoints(a=vt[2],b=vt[2]+15,pos=vtype[1],cex=2.3,col="black",lwd=2)
##--- for case 1b
spoints(a=vt[1],b=vt[2]-20,pos=vtype[2],cex=1.3,col="black",lwd=2)
spoints(a=vt[2],b=vt[2]+15,pos=vtype[2],cex=1.3,col="black",lwd=2)
##--- for case 2
spoints(a=vt[1],b=vt[2]+15,pos=vtype[3],cex=1.3,col="black",lwd=2)
##--- for case 3
spoints(a=vt[1],b=vt[2],pos=vtype[4],cex=1.3,col="black",lwd=2)
spoints(a=vt[2],b=vt[2]+15,pos=vtype[4],cex=2.3,col="black",lwd=2)
#+END_SRC

#+LABEL: fig:cases
#+ATTR_LATEX: :width 0.8 \textwidth
#+CAPTION: Illustration of the 4 cases with overlap that enter the estimate of the average daily dosis. The size of the dots indicates the second preliminary average strength B_{k}. 
#+RESULTS:
[[file:./drug-dat1a.pdf]]


*** Calculating the end dates, ${E}_1,\ldots, {E}_{k}$

\begin{align*}
{E}_{k}= \min \bigg[ {T}_{k+1}-1, \, (1-u_{k})\, (1-u_{k-1})  \, \bigg( {T}_{k} - 1+ \text{round} \left( \tfrac{D_{k} + {R}_{k}}{\styp_k} \right)\bigg) + \\
 \left(1-(1-u_{k})\, (1-u_{k-1}) \right)  \, \bigg( {T}_{k} - 1+ \text{round} \left( \tfrac{D_{k} + {R}_{k}}{{X}_{k}} \right)\bigg)\bigg]
\end{align*}

*** Calculating the leftover dose, ${R}_1,\ldots, {R}_{k}$

\begin{align*}
{R}_{k} = \Big( D_{k-1} + {R}_{k-1} - {X}_{k-1} \left( {E}_{k-1} - {T}_{k-1} \right) \Big) \, u_{k}.\end{align*}



* User interface

work in progress

#+BEGIN_SRC R  :results output raw drawer  :exports code  :session *R* :cache yes 
library(heaven)
d <- dpp()
drug(d, firstdrugname) <- atc("a")
drug(d, firstdrugname, add=TRUE) <- atc("b")
drug(d, firstdrugname) <- pack(c(50, 75, 100, 125), 
                               min = c(10, 50, 25, 50), 
                               max = c(75, 200, 150, 150), 
                               def = c(50, 100, 100, 125))
drugdb(d, add=FALSE, id=pnr) <- recept_data
admdb(d) <- datoer
period(d) <- c("2012-01-01", "2015-05-01")
N(d) <- 2
process(d,id=3000)
#+END_SRC

#+RESULTS[<2016-11-01 09:58:54> 80afc7a00ee5137b6143534504d7bb50deb33711]:
:RESULTS:
Error: could not find function "dpp"
Error: could not find function "atc"
Error: could not find function "atc"
 Error: could not find function "pack"
Error: object 'recept_data' not found
Error: object 'datoer' not found
Error in period(d) <- c("2012-01-01", "2015-05-01") : 
  object 'd' not found
Error in N(d) <- 2 : object 'd' not found
Error: could not find function "process"
:END:


** Output

The output consists of:

-  ${B}_1, \ldots, B_{{K}}$: Starting dates for each prescription
   period.
-  ${E}_1, \ldots, E_{{K}}$: End dates for each prescription period.
-  ${X}_1, \ldots, {X}_{{K}}$: Calculated dose for each prescription
   period.

bibliographystyle:chicago
bibliography:heaven.bib



* HEADER :noexport:

#+TITLE: From \texttt{\%x\_recepter} to \texttt{Rcpp}: a mathematical formulation of the algorithm, a new R-user interface and an efficient implementation
#+AUTHOR: Helene Charlotte Rytgaard and Thomas Alexander Gerds 
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:t todo:t pri:nil tags:not-in-toc author:t
#+LaTeX_CLASS: org-article
#+LaTeX_HEADER:\usepackage{authblk}
# #+LaTeX_HEADER:\author{Helene Charlotte Rytgaard and Thomas Alexander Gerds}
#+LaTeX_HEADER:\newcommand{\EE}{\mathbb{E}}
#+LaTeX_HEADER:\newcommand{\one}{1}
#+LaTeX_HEADER:\newcommand{\VV}{\mathbb{V}}
#+LaTeX_HEADER:\newcommand{\PP}{\mbox{P}}
#+LaTeX_HEADER:\newcommand{\norm}{\mathcal{N}}
#+LaTeX_HEADER:\newcommand{\lag}{N}
#+LaTeX_HEADER:\newcommand{\str}{S}
#+LaTeX_HEADER:\newcommand{\smin}{s^{\min}}
#+LaTeX_HEADER:\newcommand{\smax}{s^{\max}}
#+LaTeX_HEADER:\newcommand{\styp}{s^{*}}
#+LaTeX_HEADER:\newcommand{\period}{[a,b]}
#+LaTeX_HEADER:\newcommand{\periodK}{\ensuremath{[T_k,T_{k+1})}}
#+LaTeX_HEADER:\newcommand{\K}{K}
#+LaTeX_HEADER:\newcommand{\kk}{k}
#+LaTeX_HEADER:\newcommand{\D}{D}
#+LaTeX_HEADER:\newcommand{\B}{B}
#+LaTeX_HEADER:\newcommand{\E}{E}
#+LaTeX_HEADER:\newcommand{\XX}{X}
#+LaTeX_HEADER:\newcommand{\LL}{L}
#+LaTeX_HEADER:\newcommand{\QQ}{Q}
#+LaTeX_HEADER:\newcommand{\Ru}{R}
#+LaTeX_HEADER:\newcommand{\GG}{G}
#+LaTeX_HEADER:\newcommand{\T}{T}
#+LaTeX_HEADER:\newcommand{\st}{s}
#+LaTeX_HEADER:\newcommand{\Nn}{N}
#+LaTeX_HEADER:\newcommand{\A}{A}
#+LaTeX_HEADER:\newcommand{\C}{C}
#+LaTeX_HEADER:\newcommand{\uu}{u}
#+LaTeX_HEADER:\newcommand{\vv}{v}
#+LaTeX_HEADER:\newcommand{\zz}{z}
#+LaTeX_HEADER:\newcommand{\ww}{w}
#+LaTeX_HEADER:\newcommand{\M}{M}
#+LaTeX_HEADER:\newcommand{\I}{I}
#+LaTeX_HEADER:\newcommand{\RR}{R}
# #+LaTeX_HEADER:\affil{Department of Biostatistics, University of Copenhagen, Copenhagen, Denmark}
#+PROPERTY: header-args session *R*
#+PROPERTY: header-args cache yes

