* Introduction

The Danish National Prescription Registry (NCBI) provides
individual-level data on all prescription drugs sold in Danish
community pharmacies since 1994 citep:kildemoes2011danish. Effects and
side effects of drugs can be assessed in a Danish nation wide registry
studies. For this the prescription data are linked to the cause of
death register and other Danish registries
citep:thygesen2011introduction.

This document describes a complex algorithm for the computation of
drug exposure strength and length relative to a prespecified study
period \period. Note that the start of the study period has to be
after the start of the registry.



* Drug prescription data

We describe the data of a single person who has purchased the drug of
interest at ${K}$ different dates in the study period \period. The
setup can easily be generalized to multiple individuals. The set of
ordered drug purchase dates for one individual is denoted as
\begin{equation*}
{T}_1< \cdots< {T}_{K}.
\end{equation*}
One package of each drug product is defined by the drug strength
\(\str\) of the smallest unit (e.g., one pill or half a pill) and the
amount of such units that it contains. For each drug we distinguish
\(J\ge 1\) different package types according to the different
strengths: \(\str_1 <\dots< \str_J\). 
 Note that the original SAS
macro allowed at most 4 different package types. For each drug strength
\(\str_j\) the values \(\smin_j\), \(\smax_j\), \(\styp_j\) define the
minimal, maximal and typical dose per day, respectively. Since
\(\smin_j\) is the smallest dose possible, we must have \(\str_j= p_j
\smin_j\) for some integer \(p_j\ge 1\). The number of
smallest units, \(\smin_j\), of type \(j\) purchased on date \(T_k\)
is denoted by \(n_{jk}\). For each drug strength \(S_j\) we have
\(G_{jk}\ge 0\) purchases on date \(T_k\). For \(g=1,\ldots, G_{jk}\),
we let \(\text{pn}_{gk}\) denote the number of packages and \(\text{ps}_{gk}\) denote
the package size of purchase \(g\).  Thus, the total amount \(D_k\) of
the drug purchased on date \(T_k\) is given by the formula
\begin{align*}
D_k=
 \sum_{j=1}^J \,\left( \sum_{g=1}^{G_{jk}} \text{pn}_{gk} \, \text{ps}_{gk} \right) 
\str_j = 
 \sum_{j=1}^J \,
\left( \sum_{g=1}^{G_{jk}} \text{pn}_{gk} \,\text{ps}_{gk} \right) 
p_j \smin_j = 
 \sum_{j=1}^J n_{jk}\smin_{j},
\end{align*}
such that \( n_{jk} = 
\left( \sum_{g=1}^{G_{jk}} \text{pn}_{gk} \, \text{ps}_{gk} \right) 
p_j\). 


#+BEGIN_SRC R :results output raw drawer  :exports none :session *R*  
if (system("echo $USER",intern=TRUE)=="tag")
    setwd("~/research/SoftWare/heaven/worg/")
else
    setwd("~/research/Software/medicin-macro/heaven/worg/")
#+END_SRC

#+RESULTS[<2016-10-17 16:50:14> 0862612a285251181b55a1c4c66caec26359f50d]:
:RESULTS:
Error: unexpected 'else' in "else"
:END:


#+BEGIN_SRC R :results graphics :file "./drug-dat1a.pdf" :exports none  :session *R* 
par(mar=c(3.1,3.1,3.1,3.1))

plot(0,0,type="n",xlim=c(0,100),ylim=c(0,100),xlab="Calendar time",ylab="", 
     yaxt='n', xaxt='n', axes=FALSE)

vt <- c(15, 50, 80)

axis(1, at=vt, labels=c(expression(T[k-1]), expression(T[k]), expression(T[k+1])))
axis(1, at=seq(0, 100, by = 5), labels=rep(NA, 21))

vtype <- 100-c(2.5, 5+2.5, 5+5+2.5, 5+5+2.5+2.5)/18*100

axis(4, at=vtype, labels=c("(I)", "(II)", "(IIIa)", "(IIIb)"),
     las=2, cex.axis=1.1, tck=0.0, lwd=0)

abline(h = 100-5/18*100)
abline(h = 100-10/18*100)

abline(v = vt[1], lty=2)
abline(v = vt[2], lty=2)
abline(v = vt[3], lty=2)

points(vt[1], vtype[1], pch=15, cex=1.3, bg="black")
points(vt[1], vtype[2], pch=17, cex=1.3, bg="black")
points(vt[1], vtype[3], pch=15, cex=1.3, bg="black") 
points(vt[1], vtype[4], pch=19, cex=1.3, bg="black")

points(vt[2], vtype[1], pch=15, cex=1.3, bg="black")
points(vt[2], vtype[2], pch=17, cex=1.3, bg="black")
points(vt[2], vtype[3], pch=15, cex=1.3, bg="black")
points(vt[2], vtype[4], pch=17, cex=1.3, bg="black")

points(vt[3], vtype[3], pch=15, cex=1.3, bg="black")

t12I    <- (vt[2]-vt[1])/1.25+vt[1]
t23I    <- (vt[3]-vt[2])/1.1+vt[2]
t12IIIa <- (vt[2]-vt[1])/1.5+vt[1]

segments(x0=t12I,x1=t12I,y0=vtype[1]-1,y1=vtype[1]+1,lwd=1)
segments(x0=t23I,x1=t23I,y0=vtype[1]-1,y1=vtype[1]+1,lwd=1)
segments(x0=t12IIIa,x1=t12IIIa,y0=vtype[3]-1,y1=vtype[3]+1,lwd=1)

segments(x0=vt[1],x1=t12I,y0=vtype[1],y1=vtype[1],lwd=1)
segments(x0=vt[2],x1=t23I,y0=vtype[1],y1=vtype[1],lwd=1)

segments(x0=vt[1],x1=vt[2],y0=vtype[2],y1=vtype[2],lwd=1)

segments(x0=vt[1],x1=t12IIIa,y0=vtype[3],y1=vtype[3],lwd=1)
segments(x0=vt[2],x1=vt[3],y0=vtype[3],y1=vtype[3],lwd=1)

segments(x0=vt[1],x1=vt[2],y0=vtype[4],y1=vtype[4],lwd=1)

legend("topleft", c(expression(S[1]), expression(S[2]), bquote(S[1]~"or"~S[2])),
       pch=c(19, 17, 15),# bty = "n"
       bg="gray90")

#+END_SRC



#+RESULTS[<2016-10-17 16:47:59> 48854c356af0ca07dbf4d5ef0fd83efe8cba1a44]:
[[file:./drug-dat1a.pdf]]
file:./drug-dat1a.pdf

#+LABEL: fig:1
#+ATTR_LATEX: :width 0.7 :height 0.3 \textwidth
#+CAPTION: label til figure


#+BEGIN_SRC R :results graphics :file "./drug-dat2a.pdf" :exports none  :session *R* 
par(mar=c(3.1,3.1,3.1,3.1))

plot(0,0,type="n",xlim=c(0,100),ylim=c(0,100),xlab="Calendar time",ylab="", 
     yaxt='n', xaxt='n', axes=FALSE)
#title(main="Case II")

set.seed(9)
vt <- sort(round(sample(100, 5)/5)*5)

axis(1, at=vt, labels=c(expression(T[k-4]), expression(T[k-3]), expression(T[k-2]), expression(T[k-1]), expression(T[k])))
axis(1, at=seq(0, 100, by = 5), labels=rep(NA, 21))

abline(v = vt[1], lty=2)
abline(v = vt[2], lty=2)
abline(v = vt[3], lty=2)
abline(v = vt[4], lty=2)
abline(v = vt[5], lty=2)

vtype <- c(25, 75)
axis(4, at=vtype, labels=c(expression(I[k]^(2)), expression(I[k]^(1))),
     las=2, cex.axis=1.1, tck=0.0, lwd=0)

abline(h = 50)

##--- for w=2
points(vt[1], vtype[1], pch=15, cex=1.3, bg="black")
points(vt[2], vtype[1], pch=15, cex=1.3, bg="black")
points(vt[3], vtype[1], pch=15, cex=1.3, bg="black", col="red")
points(vt[4], vtype[1], pch=15, cex=1.3, bg="black", col="red")
points(vt[5], vtype[1], pch=15, cex=1.3, bg="black", col="red")

segments(x0=vt[1],x1=vt[2],y0=vtype[1],y1=vtype[1],lwd=1)

t32 <- (vt[3]-vt[2])/2+vt[2]
segments(x0=vt[2],x1=t32,y0=vtype[1],y1=vtype[1],lwd=1)
segments(x0=t32,x1=t32,y0=vtype[1]-1,y1=vtype[1]+1,lwd=1)

segments(x0=vt[3],x1=vt[4],y0=vtype[1],y1=vtype[1],lwd=2, col="red")
segments(x0=vt[4],x1=vt[5],y0=vtype[1],y1=vtype[1],lwd=2, col="red")

##--- for w=1
points(vt[1], vtype[2], pch=17, cex=1.3, bg="black")
points(vt[2], vtype[2], pch=19, cex=1.3, bg="black")
points(vt[3], vtype[2], pch=19, cex=1.3, bg="black")
points(vt[4], vtype[2], pch=17, cex=1.3, bg="black", col="red")
points(vt[5], vtype[2], pch=17, cex=1.3, bg="black", col="red")

segments(x0=vt[1],x1=vt[2],y0=vtype[2],y1=vtype[2],lwd=1)

t32 <- (vt[3]-vt[2])/2+vt[2]
segments(x0=vt[2],x1=t32,y0=vtype[2],y1=vtype[2],lwd=1)
segments(x0=t32,x1=t32,y0=vtype[2]-1,y1=vtype[2]+1,lwd=1)

segments(x0=vt[3],x1=vt[4],y0=vtype[2],y1=vtype[2],lwd=1)
points(vt[4], vtype[2], pch=17, cex=1.3, bg="black", col="red")
segments(x0=vt[4],x1=vt[5],y0=vtype[2],y1=vtype[2],lwd=2, col="red")

legend("topleft", c(expression(S[1]), expression(S[2]), bquote(S[1]~"or"~S[2])),
       pch=c(19, 17, 15),# bty = "n"
       bg="gray90")
#+END_SRC


#+RESULTS:
[[file:./drug-dat2a.pdf]]o
#+LABEL: fig:2
#+ATTR_LATEX: :width 0.7 \textwidth
#+CAPTION: label til figure


* Hospital admission data

Hospitals usually deliver drugs for their patients. It is therefore
hensigtsmaessig to take into account periods of hospitalization in the
calculation of exposure lengths. For a single individual we define up
to \(Q\) periods of hospitalization by the admission dates
${L}_1,\ldots, {L}_{{Q}}$ and the corresponding discharge dates
${R}_1,\ldots, {R}_{{Q}}$. 

We compute the number of days hospitalized in the period \(\periodK\)
as:
\begin{align*} 
{A}_{k} &= \sum_{q=1}^{{Q}} \max \big( 0,\,\min \left({T}_{k+1},{R}_{q}\right) - \max\left({T}_{k}, {L}_{q}\right)
\big).
\intertext{Accordingly the number of non-hospitalized days in \(\periodK\) is:}
H_k &= \left({T}_{k+1} - {T}_{k}\right) - {A}_{k}.
\end{align*}

FIXME: 
- need to limit to the study period \period?
- is the day \(T_{k+1}\) included in \periodK or not?}[3cm]

* Exposure strength and exposure lengths

The aim is to calculate the ends of the exposure periods \(E_k\) and
for each exposure period the exposure strength per day \(X_k\). The
calculations of exposure are based on the drug prescription data and
the hospitalization dates and depend further on an integer \(\lag\)
that defines the number of prescription dates back in time to use in
the calculations of exposure in a given period \periodK.

To express the exposure in period \(\periodK\) we first note that
based on the total drug purchase on date \(T_k\) the individual can be
exposed at most \(n_k=\sum_{j=1}^J n_{jk}\) days. 

We use the following notation to indicate if the maximal number of
exposure days exceeds the number of non-hospitalized days in period \periodK:
\begin{align*} 
u_{k} = \begin{cases}
0, & n_{k} \le H_k\\
1, & n_{k} > H_k
\end{cases}.
\end{align*}

Furthermore, we use  \(\str_{j(k)}\) to denote the nearest of the predefined pill strengths not
        exceeding the average strength computed for a period \(T_k\), that
        is, the index \(j(k)\) is defined as, 
      \begin{align*}
       j(k) = \max
    \left\lbrace 
 \ell \in \lbrace 1, \ldots, J\rbrace \, :\,  S_\ell \le 
 \frac{1}{c_{k}}  \sum_{j=1}^J \one \lbrace n_{jk}>0\rbrace\, S_{j}
 \right\rbrace. 
      \end{align*}
where \(c_k = \sum_{j=1} ^J \one \lbrace n_{jk}>0\rbrace\, G_{jk}\) is the
number of different drug strengths purchased on date \(T_k\) and \( \frac{1}{c_{k}} \sum_{j=1}^J \one \lbrace n_{jk}>0\rbrace\,
S_{j}\) is the average strength for period \(T_k\). Recall again, that \(c_k\) was the number of different drugs
strengths purchased on date \(T_k\),
      \(c_k = \sum_{j=1}^J \one \lbrace n_{jk} >0\rbrace\). \\

We distinguish between two periods to be used for calculating an
average daily dose, 
\begin{align*}
 {I}^{(1)}_{k} = \big\lbrace \max \big( &\min \lbrace \ell\in \lbrace 1, \ldots, J\rbrace \, :\, u_\ell = \cdots =
 u_{k-1} =1 \rbrace, \\
 &  \min \lbrace \ell\in \lbrace 1, \ldots, J\rbrace \,:\,\str_{j(\ell)} = \cdots = \str_{j(k)}  \rbrace \big), \ldots, k-1 \big\rbrace,
  \end{align*}

and 
\begin{align*}
{I}^{(2)}_{k} = \big\lbrace \min \lbrace \ell\in \lbrace 1, \ldots, J\rbrace\, : \,u_\ell = \cdots = u_{k-1} =1 \rbrace, \ldots, k-1\big\rbrace,
\end{align*}
Note that \(I^{(2)}_k\) begins on the earliest date \(T_{i_0}\) from
which the sequence of prescriptions up to time \(T_k\) provides a
large enough amount of drugs to cover the corresponding number of days
between \(T_{i_0}\) and \(T_k\), whereas \(I^{(1)}_k\) also takes into
account that the average doses along the sequence must be the
same. The periods \(I_k^{(1)}\) and \(I_k^{(2)}\) are illustrated in
Figure  ref:fig:2.   The average daily dose in the period \(I^{(w)}_k\) is then defined as,
\begin{align*}
 M^{(w)}_k =   \frac{
     \sum_{\ell \in I^{(w)}_k} \, D_\ell}{ \sum_{\ell \in I^{(w)}_k} \, H_\ell}, \qquad w = 1, 2. 
\end{align*}
At last, we define two binary variables to indicate whether the level
of the calculated average dose for \(w=2\) is below/above the relevant minimal/maximal daily doses, 
\begin{align*}
v^{\max}_k = \one \left\lbrace M^{(2)}_k > \smax_{j(k)}
 \right\rbrace, \qquad
v^{\min}_k = \one \left\lbrace M^{(2)}_k  < \smin_{j(k)}
 \right\rbrace.
\end{align*}



*** Calculating the doses, ${X}_1, \ldots, {X}_{{K}}$

#+BEGIN_SRC latex :export results :eval t
          The average exposure strength \( X_k\) per day for period \(\periodK\)  is
          computed as follows. 
 An illustration of the three different cases can be found in
 Figure ref:fig:1.  
          \begin{align*} 
          &{X}_{k} = (1-u_k)\, (1-u_{k-1}) \, \styp_k
          \\ & \qquad + \, u_{k-1}\, 1\{\str_{j(k){-}1}=\str_{j(k)}\} \,\,\left(
\min \left\lbrace
  \underset{p \in \mathbb{N}}{\text{argmin}}  \left\vert M^{(1)}_k  - 
   p\cdot \smin_{j(k)}\right\vert \cdot \smin_{j(k)} \right\rbrace
  \right)
   \\ & \qquad +
          \,\Big( u_{k} \,(1-u_{k-1}) + u_{k-1} 1\{\str_{j(k)-1}\ne \str_{j(k)}\} \Big)\,
  \Big( v^{\max}_k \, \smax_{j(k)} + v^{\min}_k \, \smin_{j(k)} + 
  (1- v^{\max}_k)(1- v^{\min}_k) \styp_{j(k)}\Big).
          \end{align*}
          Note that
          \(\left(\min \left\lbrace \underset{p \in \mathbb{N}}{\text{argmin}} \left\vert
              M^{(1)}_k - p\cdot \smin_{j(k)}\right\vert \cdot
            \smin_{j(k)}\right\rbrace\right) \) is the rounding of the average daily
          dose \( M^{(1)}_k\) to the nearest factor of the relevant
          minimal dose \(\smin_{j(k)}\). 

#+END_SRC

#+RESULTS:
#+BEGIN_LaTeX
The average exposure strength \( X_k\) per day for period \(\periodK\)  is
          computed as follows.          \begin{align*} 
          &{X}_{k} = (1-u_k)\, (1-u_{k-1}) \, \styp_k
          \\ & \qquad + \, u_{k-1}\, 1\{\str_{j(k){-}1}=\str_{j(k)}\} \,\,\left(
\min \left\lbrace
  \underset{p \in \mathbb{N}}{\text{argmin}}  \left\vert M^{(1)}_k  - 
   p\cdot \smin_{j(k)}\right\vert \cdot \smin_{j(k)} \right\rbrace
  \right)
   \\ & \qquad +
          \,\Big( u_{k} \,(1-u_{k-1}) + u_{k-1} 1\{\str_{j(k)-1}\ne \str_{j(k)}\} \Big)\,
  \Big( v^{\max}_k \, \smax_{j(k)} + v^{\min}_k \, \smin_{j(k)} + 
  (1- v^{\max}_k)(1- v^{\min}_k) \styp_{j(k)}\Big).
          \end{align*}
          Note that
          \(\left(\min \left\lbrace \underset{p \in \mathbb{N}}{\text{argmin}} \left\vert
              M^{(1)}_k - p\cdot \smin_{j(k)}\right\vert \cdot
            \smin_{j(k)}\right\rbrace\right) \) is the rounding of the average daily
          dose \( M^{(1)}_k\) to the nearest factor of the relevant
          minimal dose \(\smin_{j(k)}\).
#+END_LaTeX


*** Calculating the end dates, ${E}_1,\ldots, {E}_{k}$

\begin{align*}
{E}_{k}= \min \bigg[ {T}_{k+1}-1, \, (1-u_{k})\, (1-u_{k-1})  \, \bigg( {T}_{k} - 1+ \text{round} \left( \tfrac{D_{k} + {R}_{k}}{\styp_k} \right)\bigg) + \\
 \left(1-(1-u_{k})\, (1-u_{k-1}) \right)  \, \bigg( {T}_{k} - 1+ \text{round} \left( \tfrac{D_{k} + {R}_{k}}{{X}_{k}} \right)\bigg)\bigg]
\end{align*}

*** Calculating the leftover dose, ${R}_1,\ldots, {R}_{k}$

\begin{align*}
{R}_{k} = \Big( D_{k-1} + {R}_{k-1} - {X}_{k-1} \left( {E}_{k-1} - {T}_{k-1} \right) \Big) \, u_{k}.\end{align*}



* User interface

#+BEGIN_SRC R  :results output raw drawer  :exports results  :session *R* :cache yes 
obj <- dpp()
period(obj) <- as.Date("1995-01-01","2011-01-01")
drugdb(obj,pnr~eksd) <- recipe.db
admdb(obj,pnr~inddato+uddato) <- lpr.db
drug(obj,~painkiller) <- atc("B097BN3V")
dosis(obj,~painkiller) <- package(value,default=75,min=75,max=150)
dosis(obj,~painkiller) <- package(value,default=100,min=400,max=100)
process(obj,id=17)
#+END_SRC

#+RESULTS[<2016-10-27 15:06:31> 51aad094598f9a1103cb0485b259143796a0aa28]:
:RESULTS:
Error: could not find function "dpp"
Error in period(obj) <- as.Date("1995-01-01", "2011-01-01") : 
  object 'obj' not found
Error: object 'recipe.db' not found
Error: object 'lpr.db' not found
Error: could not find function "atc"
Error: could not find function "package"
Error: could not find function "package"
Error: could not find function "process"
:END:


** Output

The output consists of:

-  ${B}_1, \ldots, B_{{K}}$: Starting dates for each prescription
   period.
-  ${E}_1, \ldots, E_{{K}}$: End dates for each prescription period.
-  ${X}_1, \ldots, {X}_{{K}}$: Calculated dose for each prescription
   period.

bibliographystyle:chicago
bibliography:heaven.bib




* HEADER :noexport:

#+TITLE: From \texttt{\%x\_recepter} to \texttt{Rcpp}: a new user interface and an efficient algorithm
#+AUTHOR: Helene Charlotte Rytgaard and Thomas Alexander Gerds 
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:t todo:t pri:nil tags:not-in-toc author:t
#+LaTeX_CLASS: org-article
#+LaTeX_HEADER:\usepackage{authblk}
# #+LaTeX_HEADER:\author{Helene Charlotte Rytgaard and Thomas Alexander Gerds}
#+LaTeX_HEADER:\newcommand{\EE}{\mathbb{E}}
#+LaTeX_HEADER:\newcommand{\one}{1}
#+LaTeX_HEADER:\newcommand{\VV}{\mathbb{V}}
#+LaTeX_HEADER:\newcommand{\PP}{\mbox{P}}
#+LaTeX_HEADER:\newcommand{\norm}{\mathcal{N}}
#+LaTeX_HEADER:\newcommand{\lag}{N}
#+LaTeX_HEADER:\newcommand{\str}{S}
#+LaTeX_HEADER:\newcommand{\smin}{s^{\min}}
#+LaTeX_HEADER:\newcommand{\smax}{s^{\max}}
#+LaTeX_HEADER:\newcommand{\styp}{s^{*}}
#+LaTeX_HEADER:\newcommand{\period}{[a,b]}
#+LaTeX_HEADER:\newcommand{\periodK}{\ensuremath{[T_k,T_{k+1})}}
#+LaTeX_HEADER:\newcommand{\K}{K}
#+LaTeX_HEADER:\newcommand{\kk}{k}
#+LaTeX_HEADER:\newcommand{\D}{D}
#+LaTeX_HEADER:\newcommand{\B}{B}
#+LaTeX_HEADER:\newcommand{\E}{E}
#+LaTeX_HEADER:\newcommand{\XX}{X}
#+LaTeX_HEADER:\newcommand{\LL}{L}
#+LaTeX_HEADER:\newcommand{\QQ}{Q}
#+LaTeX_HEADER:\newcommand{\Ru}{R}
#+LaTeX_HEADER:\newcommand{\GG}{G}
#+LaTeX_HEADER:\newcommand{\T}{T}
#+LaTeX_HEADER:\newcommand{\st}{s}
#+LaTeX_HEADER:\newcommand{\Nn}{N}
#+LaTeX_HEADER:\newcommand{\A}{A}
#+LaTeX_HEADER:\newcommand{\C}{C}
#+LaTeX_HEADER:\newcommand{\uu}{u}
#+LaTeX_HEADER:\newcommand{\vv}{v}
#+LaTeX_HEADER:\newcommand{\zz}{z}
#+LaTeX_HEADER:\newcommand{\ww}{w}
#+LaTeX_HEADER:\newcommand{\M}{M}
#+LaTeX_HEADER:\newcommand{\I}{I}
#+LaTeX_HEADER:\newcommand{\RR}{R}
# #+LaTeX_HEADER:\affil{Department of Biostatistics, University of Copenhagen, Copenhagen, Denmark}
#+PROPERTY: header-args session *R*
#+PROPERTY: header-args cache yes
test
